components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/util/OrganizationManagementEndpointUtil.java
components/org.wso2.carbon.identity.organization.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementDataHolder.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementServiceComponent.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java

With this change, the user will require to have the permission `/permission/admin/` to create the ROOT internally during the **first** time organization creation request for a tenant.

Improve authorization evaluation logic for ROOT organization creation

---

.github/ISSUE_TEMPLATE/config.yml
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/OrganizationsApi.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/service/OrganizationManagementService.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/resources/org.wso2.carbon.identity.organization.management.yaml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CachedBackedOrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java

When the parent organization is deleted, child organization entries should be removed from the cache. This PR will remove the entire cache by tenant domain to avoid any incorrect behaviours. However, the caching layer should be improved to only perform a cascade deletion of child orgs when the parent org is deleted (force=true).

Fix caching issue with deleting child org entries when parent is deleted

---

components/org.wso2.carbon.identity.organization.management.role.mgt.core/src/main/java/org/wso2/carbon/identity/organization/management/role/mgt/core/constants/DatabaseConstants.java
components/org.wso2.carbon.identity.organization.management.role.mgt.core/src/main/java/org/wso2/carbon/identity/organization/management/role/mgt/core/dao/OrganizationUserRoleMgtDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java

> With H2 DB 2.x COUNT(1) returns a result with column name COUNT(*) (result column name was COUNT(1) in H2 DB 1.x) referring the Column by index make it independent of the column name.

Fix required to be compatible with H2 upgrade to 2.x

---

components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/OrganizationsApi.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/OrganizationsApiService.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/BasicOrganizationResponse.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/ChildOrganization.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/GetOrganizationResponse.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/OrganizationPOSTRequest.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/OrganizationPUTRequest.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/OrganizationResponse.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/ParentOrganization.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/impl/OrganizationsApiServiceImpl.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/service/OrganizationManagementService.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/resources/org.wso2.carbon.identity.organization.management.yaml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CachedBackedOrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationRowDataCollector.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/ChildOrganizationDO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/Organization.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/ParentOrganizationDO.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImplTest.java

This PR adds the following improvements:
- Remove earlier introduced forceful deletion of child orgs (as a cascade delete).
- Change `self` as `ref` to denote the resource URI in the JSON response body.
- Add support to update the organization status.
- If parent ID is not present in the create organization request, the parent will be considered as the ROOT.
- Allow users with '/permission/admin/' assigned to to create an organization as an immediate child organization of the ROOT organization.
- Add filtering support to list organizations based on the `parentId` attribute.
- Fix server error which occurred when filtering organizations from `id` attribute.

Add improvements

---

components/org.wso2.carbon.identity.organization.management.role.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/role/management/endpoint/service/RoleManagementService.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/Organization.java
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/Constants.java
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/internal/TenantAssociationDataHolder.java
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/internal/TenantAssociationServiceComponent.java
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/listeners/TenantAssociationManagementListener.java
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

- Add the organization creator role against the created organization and org creator during onTenantCreate
- Remove TENANT_ID from UM_ORG data model
- Remove TENANT_ID from UM_ORG_ROLE data model
Part of fix https://github.com/wso2/product-is/issues/13959

Improve Tenant type organization creation without creating a tenant admin inside the tenant

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java

The count(1) function of the H2 database return a column name as count(*) and which result in syntax error when the jdbc template request for a column name count(1). As the fix for that, the column is requested by it's index instead of column name.

Fix for H2 database query issue

---

components/org.wso2.carbon.identity.organization.management.oauth2.grant/pom.xml
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/OrganizationSwitchGrant.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/OrganizationSwitchGrantValidator.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/exception/OrganizationSwitchGrantClientException.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/exception/OrganizationSwitchGrantException.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/exception/OrganizationSwitchGrantServerException.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/internal/OrganizationSwitchGrantDataHolder.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/internal/OrganizationSwitchGrantDataHolderServiceComponent.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/util/Constants.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/util/OrganizationSwitchGrantConstants.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/util/OrganizationSwitchGrantUtil.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
pom.xml

The organization administrators can have access for multiple organizations and able to switch for the authorized organizations. The organization switching grant type implements token exchange mechanism when a valid access token is present. 
- 1 -Download and put the jar inside ./repository/components/lib
- 2 - Add the following config in deployment.toml to enable the new grant type. 
```
[[oauth.custom_grant_type]]
name="organization_switch"
grant_handler="org.wso2.carbon.identity.organization.management.oauth2.grant.OrganizationSwitchGrant"
grant_validator="org.wso2.carbon.identity.organization.management.oauth2.grant.OrganizationSwitchGrantValidator"
[oauth.custom_grant_type.properties]
IdTokenAllowed=true
```
- 3 - Enable the grant type as allowed grant for the service provider

Add Organization switching grant type

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

$Subject
`userStoreManager.getUser(userId, userName);` will return a user object created with the provided username and user id. If the given two values are not matched to a same user, the returned user is incorrect/ may be not existing user

Refactor resolveUserFromResidentOrganization logic to avoid returning incorrect user object

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java

The current code return empty if the user does not exist in the first checked org.

Fix a bug in org user resolver

---

components/org.wso2.carbon.identity.organization.management.authn/src/main/java/org/wso2/carbon/identity/organization/management/authn/OrganizationAuthenticator.java
components/org.wso2.carbon.identity.organization.management.authn/src/main/java/org/wso2/carbon/identity/organization/management/authn/constant/AuthenticatorConstants.java

> When multiple organizations with same name identified, the user is prompted to select the intended organization by providing additional information. The information like description, name and id is send to the server pages as  encoded query params without passing comma separated values.

Improve sending organizations information to select org from multiple orgs

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtDataHolder.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtServiceComponent.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

In the process of sharing SaaS app to sub organization, a fragment app is created in the sub organization. The user of the fragment app should be set to tenant admin's username. But sub org tenant admin username is set as the userId of the organization created user.  Therefore the username is resolved based on the sub organization admin's username (user-id)

Hot fix for appication sharing

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> At the time of the application sharing, new fragment application is created in child org with oauth inbound application to redirect the user login to child organization. Application name wasn't set in the consumer app result in failure when redirecting to consent URL. Also the consumer app has to be removed if the fragment app creation fails.

Set application name in oauth consumer app for fragment app.

---

components/org.wso2.carbon.identity.organization.management.authn/src/main/java/org/wso2/carbon/identity/organization/management/authn/OrganizationAuthenticator.java
components/org.wso2.carbon.identity.organization.management.authn/src/test/java/org/wso2/carbon/identity/organization/management/authn/OrganizationAuthenticatorTest.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Previously used `getRuntimeParams` method returns unmodifiable map when the organization login adaptive script is not configured. The reasoning is the adaptive script creates a runtime parameter map called `common` as shown below figure and  no parameter map created if adaptive script is not used. But there can be scenarios where organization login is only required and hence the adaptive script is not necessary. In those cases, the organization login failed with exception. As a fix, the organization information like orgId and org name is stored in authentication context and retrieved when necessary.
https://github.com/wso2/product-is/issues/14383

Add authentication context param to store org information in organization login flow

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

> Fixing the bug of OrganizationManagementServerException: Unable to retrieve the organizations. when Navigating to Organizations Section against MSSQL 2019
> Fixing the bug of being unable to retrieve organizations' role list with MSSQL DB
> Properly retrieve the organization list when working with the MSSQL database
> Properly retrieve the organization's role list when working with the MSSQL database
> The problem was using an incorrect keyword called 'Limit' in the SQL query.
> Fixed by setting the offset to 0 and fetching the next result set.
> Retrieve the organization list from the new console.
> Retrieve the organization's role list from the new console.
> MSSQL Azure Edge
> Oracle JDK 11
> IS 6.0.0 alpha 3
> macOS m1 chip
> * https://github.com/wso2/product-is/issues/14365
> * …

Fixed bug: Unable to retrieve the organisation list and organisation's role list with MSSQL

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAO.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/internal/RoleManagementDataHolder.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/internal/RoleManagementServiceComponent.java

Validate users while role assignment

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> The service url builder is improved to build organization qualified urls when organization id is set in the carbon context.
https://github.com/wso2/carbon-identity-framework/pull/4229. While the fragment app is created, a tenant flow is started against the tenant domain of the application shared tenant (organization). Therefore the corresponding organization id also set in the carbon context to build correct service urls. 
Instead of adding organization id in the carbon context, the organization id can be passed along with the subsequent methods and generate service url as follows. 
`ServiceURLBuilder.create().addPath(o/<org-domain>/commonauth).build().getRelativePublicURL()`
- https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/205

Set org qualify callback url for fragment apps

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/OrgApplicationMgtDAO.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/model/MainApplicationDO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> The configured user attributes of the main application are not shared with the fragment application.
> Without updating the fragment application, retrieve the main application user claims instead. Since this section is already hidden in the fragment application. If we have updated the fragment apps, when updating the main app, it'll lead to a performance issue if we had so many shared apps bound to the main app.
> Used listeners to update the fragment app object with necessary properties using the main application, when retrieving the app.
> Can test the flow by configuring the [playground2 app](https://is.docs.wso2.com/en/5.11.0/learn/deploying-the-sample-app/#deploying-the-playground2-webapp) with OIDC protocol. Decode and check the jwt id token
> * …

Fix issue of updating the user attributes in fragment app when updating the main app

---

components/org.wso2.carbon.identity.organization.management.ext/pom.xml
components/org.wso2.carbon.identity.organization.management.ext/src/main/java/org/wso2/carbon/identity/organization/management/ext/Constants.java
components/org.wso2.carbon.identity.organization.management.ext/src/main/java/org/wso2/carbon/identity/organization/management/ext/OrganizationManagerListenerImpl.java
components/org.wso2.carbon.identity.organization.management.ext/src/main/java/org/wso2/carbon/identity/organization/management/ext/internal/OrganizationManagementExtDataHolder.java
components/org.wso2.carbon.identity.organization.management.ext/src/main/java/org/wso2/carbon/identity/organization/management/ext/internal/OrganizationManagementExtServiceComponent.java
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

> Since this component sits higher than the carbon-identity-framework component in the dependency hierarchy, there is no way to fire events. This PR add a listener so that we can implement the listener in lower level of the dependency hierarchy and fire events.
Depends on https://github.com/wso2-extensions/identity-organization-management-core/pull/11

Add initial event firing mechanism

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java

- Fix setting `UM_PERMISION_ID` as an integer when building database query to map permissions to roles.

Fix setting database query attributes considering proper datatype

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

- With B2B organization management feature, the (tenant) admin of the sub organization will resides in a parent organization. That admin user can be resides in primary or secondary user stores of the parent organizations (ex- asgardeo business users with admin access). 
- The SP_APP table keep track of the service provider apps and its owners information. In current setup, when fragment app is created, the org admin (who resides in a parent org) will be assigned as the app owner (it is the default behaviour). The app owner setting logic is further improved by passing user store domain also and the improvement is displayed in below figure.
Here the  "zoom.sadil@wso2.com" is a business user who has admin accesses and who is the owner of the organization where the SaaS app is shared.

Set domain qualified user as the fragment app owner

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Enabling root application and the fragment applications to use mapped local subject identifier for JIT provisioned users.
When an enterprise IDP is used to login to the application and user is required to have organization roles attach, local subject identifier should be used as the user identifier.

Enabling B2B main application to use local subject identifier in claim config for provisioned users.

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

>  With [this](https://github.com/wso2-extensions/identity-auth-organization-login/pull/13) approach, the application shared organizations are listed and filtered the duplicate organizations which doesn't get shared the application. Listing  the application shared organization has to be done through the same organization where the application resides. The request invoked organization ID is resolved by the `getOrganizationId()` method and it get the organizationID set in the carbon context. For IDAAS deployments even 1st level organizations resource access happen through `t/<tenant-domain>` hence the organization ID is not set in the context.
There are two possible approaches for this case,
- Remove this check due to allowing to list the shared organizations would be less harmful.
- …

Remove the restriction for requesting to get application shared organizations only from the application reside organization.

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandler.java

$Subject and fix the error that occurred when sharing application in other DB types
Column name VALUE in SP_METADATA table should be handled as \`VALUE\` only for H2.
So use a separate SQL constant `IS_FRAGMENT_APPLICATION_H2` for H2 DB usage.

Use separate SQL constant for IS_FRAGMENT_APPLICATION to be used in H2 DB

---

pom.xml

Extending the carbon user core version range to support carbon kernel 4.8.0-m1

[1.2.x] Extending carbon user core version range

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java

The current role display name check to patch role doesn't allow following scenarios
- new role name -> same as old role name (returns 409)
- There are only case differences between new role name and old role name (returns 409)
This PR fixes this issue

Check if existing role name is for the same role Id in patching role

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

> The current implementation allows authentication script configuration to be changed for fragment applications. This is not to be allowed in the future. This PR contains the implementation to block updating the authentication script configuration. 
> Block updating the authentication script configuration for fragment applications. 
> In the pre update process for the applications, check if application is fragment application. If yes, check if it's updating the authentication script. If so throw an error stating that the operation is not allowed.

Block authentication script configuration for fragment Application

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

> Fragment application deletion should only be available through the un-share option of the parent organization. Therefore the fragment application deletion is being restricted if not done through un-share option or the deletion of the main application.

Restrict fragment application deletion through sub organizations.

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/models/User.java
pom.xml

- > Check whether the UM_USER_RESIDENT_ORG_ID column is available in the UM_ORG_ROLE_USER_TABLE and add the related value for it if the column is available when creating users of a role in POST, PUT, PATCH requests.
- > Send details required to change get role by roleID API response (https://github.com/wso2-enterprise/identity-api-organization-management/pull/30)
Merge this PR after merging the following PRs
- https://github.com/wso2-extensions/identity-organization-management-core/pull/61
- https://github.com/wso2-enterprise/asgardeo-product/issues/15292

Insert orgID in the DB when creating users of a role

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java

> Prevent update role via PUT op, if the modified role display name is equal to a display name of an existing role.
> To not having two roles with the same display name.
- https://github.com/wso2-enterprise/asgardeo-product/issues/16750

Improve sub org role PUT operation validations

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java

> Get users with null resident org ids for the get role request to improve backward compatibility. And fix the user resident org id resolving problem occurred due to the inability of resolving request invoking org id when we create a role through listeners.

Get users with null resident org ids for the get role request.

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/internal/RoleManagementDataHolder.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/internal/RoleManagementServiceComponent.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/models/Group.java
pom.xml

> Resolve group resident org id when assigning a group to a sub-org role if DB column is available.
> Assign parent org groups to a sub org role.
- https://github.com/wso2-extensions/identity-organization-management-core/pull/64

Resolve group resident org when assigning a group to a role.

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

- Setting the skipLogoutConsent property value to `true` for the shared application to skip the logout consent prompting when the logout is performed from the sub organizations.
- Properly logout the user from the sub organization.
- Set `skipLogoutConsent` property to `true` from the listener.

Set skip logout consent prop to shared apps

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListenerTest.java
pom.xml

> Purpose of this is to restrict application creation in sub-organizations. 
>  Restrict application creation in sub-organizations in PCC and IS+B2B connector setup.

Restrict application creation in sub-organizations in PCC and IS+B2B connector setup 

---

pom.xml

> $subject
The following console output was given by the Jenkins job. It says, auth service is failed to build due to role service is not available. As a temp fix, the order of the modules changes in order to build the role service first.

Fix build issue

---

components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreService.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/dao/UserInvitationDAO.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/dao/UserInvitationDAOImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/internal/UserInvitationMgtServiceComponent.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/listener/OrgSharedUserOperationEventListener.java

* $subject
* In this initial implementation, when a user is deleted then if there are any associations to the child organizations, they will be removed before deleting the user.

Add organization shared user listener

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreService.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/dao/UserInvitationDAO.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/dao/UserInvitationDAOImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/listener/OrgSharedUserOperationEventListener.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/models/SharedUserAssociation.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/test/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImplTest.java

* $subject
* Added the `doPreSetUserClaimValuesWithID` to restrict the user claim update for shared users.
* Made the followings configurable.
- Expiry time of the invitations.
- Default user store domain for users in the parent organization.
- Default user redirection URL for invitation acceptance.
* Improve `doPreDeleteUserWithID` listener.

Improve organization user invitation and user sharing

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> Changed the name of the IdP created for organization login to "SSO".
This is affected only for newly created sub organizations
Related Issue
- https://github.com/wso2-enterprise/asgardeo-product/issues/19350

Change "Organization Login" IDP name to "SSO"

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java
pom.xml

When passing a boolean value for a boolean field in Mysql, if a string is being passed as the boolean value, it should be a digit, instead of "true" or "false". Current implementation supports only for mssql. This effort adds the fix for mysql db type.
Fixes: https://github.com/wso2/product-is/issues/16687
###Note:
This PR should get merged after this PR https://github.com/wso2/identity-organization-management-core/pull/81

Add db type check for mysql for writing boolean value shareWithAllChildren

---

components/org.wso2.carbon.identity.organization.config.service/pom.xml
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/OrganizationConfigManager.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/OrganizationConfigManagerImpl.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/constant/OrganizationConfigConstants.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/exception/OrganizationConfigClientException.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/exception/OrganizationConfigException.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/exception/OrganizationConfigServerException.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/internal/OrganizationConfigServiceComponent.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/internal/OrganizationConfigServiceHolder.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/model/ConfigProperty.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/model/DiscoveryConfig.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/util/Utils.java
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Issue: https://github.com/wso2/product-is/issues/16728

Add organization configuration service

---

components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/OrganizationConfigManagerImpl.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/constant/OrganizationConfigConstants.java

Issue: https://github.com/wso2/product-is/issues/16728

Validate if the discovery attribute key is supported

---

components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/listener/OrgSharedUserOperationEventListener.java

Enable the organization shared user op event listener

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandler.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtServiceComponent.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/ApplicationSharingManagerListenerImpl.java
pom.xml

Added a new event handler to manage user attributes for the sub-organization. This handler will be triggered for the following events
- POST_SHARE_APPLICATION
- POST_APP_USER_ATTRIBUTE_UPDATE
- POST_DELETE_LOCAL_CLAIM
- POST_DELETE_EXTERNAL_CLAIM
- POST_UPDATE_LOCAL_CLAIM
- POST_UPDATE_EXTERNAL_CLAIM
- POST_ADD_EXTERNAL_CLAIM
Related issue :
- https://github.com/wso2/product-is/issues/16702
Related Prs:
- https://github.com/wso2/carbon-identity-framework/pull/4948
- https://github.com/wso2/carbon-identity-framework/pull/4958

Add event handler to manage user attributes for the sub-organizations

---

components/org.wso2.carbon.identity.organization.management.claim.provider/pom.xml
components/org.wso2.carbon.identity.organization.management.claim.provider/src/main/java/org/wso2/carbon/identity/organization/management/claim/provider/OrganizationClaimProvider.java
pom.xml

According to the organization bound token improvement, the user accessing organization should be fetch from the newly introduced attributes of the authenticated user object. 
Also the user's resident organization information also need to fetched and added to the ID token as an additional claim.
- https://github.com/wso2/product-is/issues/16365
Depends on
- https://github.com/wso2/carbon-identity-framework/pull/4915

Improve claim provider according to the organization bound token improvements

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManager.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Added two new services:
1. check whether a given main app is shared with a given org
2. retrieve the main application id for a given shared app
Part of: https://github.com/wso2/product-is/issues/16363

New services to derive whether app is shared to a given org /  get main app id

---

components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/internal/TenantAssociationDataHolder.java
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/internal/TenantAssociationServiceComponent.java
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/listeners/TenantAssociationManagementListener.java
pom.xml

When tenants are created by tenant management API, those tenants are not associated to an organization. In order to provide the B2B capabilities for those tenants, those tenants should be associated for a root organization where an organization hierarchy can be made.
The tenant's associated organization ID can be either defined at tenant creation level or if not a generated UUID is set as its root organization ID.
- https://github.com/wso2/identity-organization-management-core/pull/89
- https://github.com/wso2/product-is/issues/16712

Create root organization for tenant created without organizations.

---

components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/AttributeBasedOrganizationDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/EmailDomainBasedDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManager.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManagerImpl.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/constant/DiscoveryConstants.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/internal/OrganizationDiscoveryServiceComponent.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/listener/OrganizationDiscoveryUserOperationListener.java

Depends on https://github.com/wso2/identity-organization-management-core/pull/95
Related PR: https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/488
**Scenario 1**: Organization has mapped domains. A user is added with an email domain that is not associated with this organization.
https://github.com/wso2-extensions/identity-organization-management/assets/24982871/c9028422-002a-4419-9793-db3db54c46cb
**Scenario 2**: Organization doesn't have any mapped domains. A user is added with an email domain that is associated with a different organization.
https://github.com/wso2-extensions/identity-organization-management/assets/24982871/c8855e26-c908-42e1-9898-318a19c50638

Introduce pre add user validations for email domain discovery feature

---

components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/AttributeBasedOrganizationDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/EmailDomainBasedDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManagerImpl.java
pom.xml

Issue: https://github.com/wso2/product-is/issues/16379
Depends on: https://github.com/wso2/identity-organization-management-core/pull/100

Validate email domain format

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandler.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerDataHolder.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerServiceComponent.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
pom.xml

$Subject
SharedRoleMgtHandler handles:
- On creating a role with application audience in the primary organization, created the shared roles in the organizations where the app is already shared
- On shared app creation in sub-organization
1. Create application audience roles defined in the parent application 
2. Create organization audience roles if the shared app uses them and if the same organization role is not availble in the sub-org due to any other shared app
config to enable handler:
```
[[event_handler]]
name= "SharedRoleMgtHandler"
subscriptions =["POST_ADD_ROLE_V2_EVENT", "POST_SHARE_APPLICATION"]
```
SharedRoleMgtListener handles:
- On deleting a shared app(may be due to unsharing the app from given org/ delete the main app and due to that deleting shared app) deleting roles …

Add shared role managing event handler and event listener

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

with this PR
- When the app name of shared app gets updated, app name of fragment apps also will update
- Blocked the app name update of fragments app through APIS.
Fixes for 
- https://github.com/wso2/product-is/issues/17101

Manage application name update of fragment apps.

---

components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/handler/OrganizationManagementAuthzHandler.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingDataHolder.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingServiceComponent.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/util/OrganizationSharedUserUtil.java

- Added a  util method to resolve the user ID if the given user ID is an associated user ID of the given organization.
- Used that util in the organization management authorization handler which is based on the user permissions.

Add util method to get the user ID of an associated user

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
pom.xml

If the legacy authz runtime is false, always set the roles claim as a requested claim of the shared application
Part of https://github.com/wso2/product-is/issues/16363

Always set roles claim as a requested claim of the shared application if legacy authz runtime is false

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingDataHolder.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingServiceComponent.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java
pom.xml

Assign user to the administrator role of the organization

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml

```
ERROR {org.wso2.carbon.identity.api.dispatcher.core.DefaultExceptionMapper} - Server encountered an error while serving the request. java.lang.NoClassDefFoundError: org/wso2/carbon/CarbonConstants
at org.wso2.carbon.identity.organization.management.application.listener.FragmentApplicationMgtListener.doPostGetServiceProvider(FragmentApplicationMgtListener.java:247)
at org.wso2.carbon.identity.application.mgt.listener.DefaultApplicationResourceMgtListener.doPostGetApplicationByResourceId(DefaultApplicationResourceMgtListener.java:189)
```
Fix the class def not found error introduced with https://github.com/wso2-extensions/identity-organization-management/pull/275
Part of https://github.com/wso2/product-is/issues/16363

Class def not found error fix

---

components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManager.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManagerImpl.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/dao/OrganizationDiscoveryDAO.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/dao/OrganizationDiscoveryDAOImpl.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/model/DiscoveryOrganizationsResult.java
pom.xml

Issue: https://github.com/wso2/product-is/issues/16379

Implement pagination for get discovery attributes of organizations

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

> $subject
- https://github.com/wso2/product-is/issues/17382

Fix user sharing issue

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java
pom.xml

> Remove the usage of thread local and use the carbon context to fetch the authenticated user's resident organization.
- https://github.com/wso2/carbon-kernel/pull/3716

Get user resident organization from carbon context

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> Having the user_organization claim as a runtime claim of the organization is enough to resolve the user's organization set by the organization authenticator upon successful identity federation.
- https://github.com/wso2/product-is/issues/16365

Skip adding user_organization claim as service provider requested attribute

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/util/OrganizationSharedUserUtil.java

Fixes for 
- https://github.com/wso2/product-is/issues/17687

Fix issues when the managedOrg claim is not available.

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListener.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
pom.xml

>  $subject
1 - Block claim updates for shared users.
2 - Fail user invite if an invitation is send for user with the same name who already exist.
3 - Allow inviting shared users to another organization by fetching the email claim of the original user.

User invitation improvements and block shared user update

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandler.java

When a new attribute mapping is created, it is not added to the suborganizations but when a new external claim is added to that attribute mapping, the claim is copied to the suborganization. Because the attribute mapping of the suborganization does not exist, this throws an error.
This PR contains the following changes.
- Captures the `POST_ADD_CLAIM_DIALECT` event and copies the claim dialect to the suborganizations.
- Captures the `POST_RENAME_CLAIM_DIALECT` event and renames the claim dialect in the suborganizations.
- Captures the `POST_DELETE_CLAIM_DIALECT` event and deletes the claim dialect in the suborganizations.
This fixes the following issue.
- https://github.com/wso2/product-is/issues/17947

Propagate claim dialect changes to suborganizations

---

components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/CarbonContextCreatorValve.java
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/util/Util.java

> The organization perspective resources of the super tenant domain can be accessed via /o/<API-resource> paths. As the organization-id is not passed with organization path in the URL, the tenant domain was set to null. With this PR, it is set to the super tenant domain, as that type of organization qualified resources accesses can be made only for the super tenant domain managed organization resources.
- https://github.com/wso2/product-is/issues/18072

Allow organization qualifier for super tenant org resource access

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java

Instead of letting service URL builder to generate the context based on the information had, the path can be generated upto some extent (relative path) and pass it to the service URL builder. 
As the apps can be created from a tenant, the shared app's callback URL should be always point to the commonauth endpoint of the app resides tenant.

Fix callback generation issue for shared apps

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

A retry mechanism is needed due to the possibility of stale data in the IDN_OAUTH_CONSUMER_APPS table which would cause issues in the flow of sharing applications with sub organizations.
Stale apps exist due to the previous error where the OAuth app was not deleted while the SP was deleted as mentioned above and would cause issues to users who have previously unshared applications before the initial fix was onboarded.
A fix is done in the app sharing flow where, if there is an error related to the OAuth app already existing during the OAuth app creation, there will be a check to validate whether it is a stale app and if it is deemed to be a stale app, it will be deleted and the OAuth app creation will be retried.
- https://github.com/wso2/product-is/issues/18941

Handle OAuth Client Exists Error due to stale data

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/util/OrganizationSharedUserUtil.java
components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/models/Invitation.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/models/InvitationDO.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/models/InvitationResult.java

Part of https://github.com/wso2/product-is/issues/20014
If the invitation has
```
"properties": [
{
"key": "manageNotificationsInternally",
"value": "false"
}
]
```
Give the priority to this config regarding notification handling mechanism before checking on server level configuration.

Return confirmation code if notification handling is managed externally

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

>  When the organization is created with m2m token, the previous logic was set to not to share the user and assign roles even the owner ID is mentioned in the organization attributes.
With this PR it is improved to share and assign the role only if the organization owner ID is mentioned in the organization creation payload.

Fix organization owner not assigned for role when user-id set in organization attributes

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandler.java

Fix sub organization deletion with selected shared applications lead to NPE with username in the thread local context in the application update listeners.

Fix tenant deletion listener NPE for username.

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/handler/UserInvitationEventHandler.java

Add temp logs

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Application sharing logic should not be executed if child org list is empty.

Skip application sharing if child org list is empty.

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java

Shared roles are not available for legacy runtime and leads to errors when trying to unshare applications.

Disable shared role deletion for legacy runtime

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

If set share with all children property for an application even the tenant don't have any sub organization, the property should not be changed to `do not share`. Only change would be SSO login option should not be in the login flow. It should be seen in the login flow when you create the first sub org.
- https://github.com/wso2-extensions/identity-organization-management/pull/365

Skip adding SSO authenticator if child organization list is empty

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

The tenant domain is set here after creating an ServiceURLBuilder instance to ensure the expected tenant domain is considered when building the service url

Set tenant domain when building service url

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/test/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImplTest.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/test/java/org/wso2/carbon/identity/organization/user/invitation/management/constants/InvitationTestConstants.java

> This PR addresses the issue where users assigned to an organization admin role via groups cannot be invited to join as sub-org level admins. [issue #20377](https://github.com/wso2/product-is/issues/20377).
> Ensure that all users, regardless of whether their admin role is assigned directly or via a group, can be invited as sub-org admins from the sub-organization console.
1. **Added `getUserGroups()` method**:
- Introduced a private method `getUserGroups(String userId, String tenantDomain)` to retrieve the list of groups a user belongs to.
2. **Updated `isInvitedUserHasConsoleAccess()` method**:
- Modified this method to call `getUserGroups()`, retrieve the roles from the groups via `roleListFromUserGroups()`, and incorporate these roles into the user's total role list.
- Ensured that …

Fix: Enable Group-Assigned Organization Admins to Be Invited as Sub-Org Admins

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
pom.xml

> $purpose
- The roles admin and everyone in sub org is created when the application is shared with the sub orgs.
- Then if there only one app shared with the sub org, when we are deleting the app, the relevant roles also should be deleted.
- So we need to exclude the everyone and system role from the roles for deleting when the org is not a suborg.
- Merge after this PR : https://github.com/wso2/carbon-identity-framework/pull/5694
- https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2464

Fix system role deleting issue in sub orgs when app is deleting

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
pom.xml

Previous Behaviour : `<PROTOCOL>://<HOSTNAME>:<PORT>/t/<tenant-domain>/o/<org-id>/myaccount`
For the IDaaS setups it will be required to have the access URL in the form of below.
Ex: `<PROTOCOL>://<HOSTNAME>:<PORT>/t/<tenant-domain>/o/<org-id>/app`
With this PR it is fixed only for the MyAccount as the access URL of MyAccount of the sub-organization is used widely than the access URL of the shared console app.
There are few improvements to be made to have proper access URL for the console app. After fixing that, migration task is required to properly update the already created Console & MyAccount access URLs which might have been incorrectly set.
- https://github.com/wso2/carbon-identity-framework/pull/5749

Fix shared MyAccount portal path issue

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

FIX NPE due to missing userId in carbon context at https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationManagementServiceImpl.java#L257

FIX NPE in audit logs for organization creation

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

> $subject
No need to add previous organization roles for the sub-organization creator as the authorization runtime is enabled by default and there is no recommondation for switch back to the old authorization runtime.

Remove unwanted legacy authz runtime checks

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

When trying to delete an application, its corresponding shared apps are required to be deleted. The shared apps are deleted within a tenant flow started against the corresponding organization each shared app exist.
The audit log events are published upon certain operations like application deletion, where the request initiator information is required to be logged in order to track the operations. 
When starting a tenant flow, the request initiator information will be cleared from the context, hence we can add the username into the context, so that information can be used for the places where audit logs are published.

Set the request initiator as the shared app deletion initiator

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

> $subject
Related issue: https://github.com/wso2/product-is/issues/21118 …

Inherit discoverable property to the shared apps

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManager.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/OrgApplicationMgtDAO.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java

$subject
Related PRs: https://github.com/wso2-extensions/identity-organization-management/pull/390, https://github.com/wso2/identity-api-user/pull/202
Related issue: https://github.com/wso2/product-is/issues/21118
Merge before : https://github.com/wso2/identity-api-user/pull/202
> …

Retrieve Discoverable Applications info for Sub-Org 

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandler.java

> With this fix, we are removing the shared app retrieval of the main application when updating `isAppShared` property. We can check whether the property is updated to true before.
Issue - https://github.com/wso2/product-is/issues/21203

Improve app sharing logic during organization creation

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManager.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/OrgApplicationMgtDAO.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandler.java
pom.xml

> Fixes https://github.com/wso2/product-is/issues/21203
Reviewed with https://github.com/wso2-extensions/identity-organization-management/pull/396

Clear shared app link to improve performance of org deletion

---

.github/workflows/pr-builder.yml
components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/test/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImplTest.java
pom.xml

> Add a validation logic to verify the provided invitation user store domain is valid or not https://github.com/wso2-extensions/identity-organization-management/pull/402/files#diff-ebba2067b3fa55047938aa6006a6864220dd3d4de3854fc2894d203714e0e926R737-R746
In this effort the following improvements are made.
- https://github.com/wso2/product-is/issues/21460

Validate user store domain of the parent user invitation flow

---

components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/listener/OrganizationDiscoveryUserOperationListener.java
components/org.wso2.carbon.identity.organization.discovery.service/src/test/java/org.wso2.carbon.identity.organization.discovery.service/listener/OrganizationDiscoveryUserOperationListenerTest.java
components/org.wso2.carbon.identity.organization.discovery.service/src/test/resources/testng.xml

Fixes: https://github.com/wso2/product-is/issues/21466
When creating a sub-organization, the root organization's user is shared within the sub-organization. However, if the domain of the root user is already associated with another sub-organization, user creation fails due to a domain validation error. This validation is not necessary for shared users.
Remove the domain validation for users when the user is created as either the root tenant admin or an invited user from the parent organization. This can be achieved by checking the managed-by claim of the user.

Skip email domain validation for shared user creation

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/test/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImplTest.java
pom.xml

> $subject
- https://github.com/wso2/product-is/issues/21460
- https://github.com/wso2-extensions/identity-organization-management/pull/402

Add unit test for validate invite for sub org console role

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListenerTest.java

$subject
Issue: https://github.com/wso2/product-is/issues/21222
Fixes the first task of the above issue.
1. If the root application is marked as an API based authentication enabled application, inherit that configuration for shared apps as well
- The shared application will inherit the main application's APIBasedAuthenticationEnabled property during the shared application creation. 
- When retrieving the shared application it will inherit the main application's APIBasedAuthenticationEnabled property, **if and only if, the APIBasedAuthenticationEnabled property in the main application is true.**
| Root App APIBasedAuthenticationEnabled Property | Shared App APIBasedAuthenticationEnabled Property | Impact                                                                 | …

Inherit APIBasedAuthenticationEnabled property from parent application to the shared application

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandler.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/tests/SharedRoleMgtHandlerTest.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/resources/repository.conf/carbon.xml
pom.xml

- $subject
- From [1] role management will be enabled in the sub organization level as well. 
- With that, in the sub organization level, there will be two types of roles.
- Shared roles from the root organization (through the application sharing)
- Roles created inside the sub organization directly.
- There can be conflicts when the roles are created in the sub organization level.
- This PR contains the fixes for the following conflicting scenarios.
- Sub organization has a role named `role01` and an organization audience application will be shared from the root organization and root organization contains a role named `role01`
- App sharing will be restricted to that corresponding conflicting sub organization.
- Sub organization has a role named `role01` and already an organization …

Resolve role sharing conflicts in app sharing

---

components/org.wso2.carbon.identity.organization.resource.hierarchy.traverse.service/src/main/java/org/wso2/carbon/identity/organization/resource/hierarchy/traverse/service/strategy/FirstFoundAggregationStrategy.java
components/org.wso2.carbon.identity.organization.resource.hierarchy.traverse.service/src/main/java/org/wso2/carbon/identity/organization/resource/hierarchy/traverse/service/strategy/MergeAllAggregationStrategy.java
components/org.wso2.carbon.identity.organization.resource.hierarchy.traverse.service/src/test/java/org/wso2/carbon/identity/organization/resource/hierarchy/traverse/service/OrgResourceResolverServiceTest.java

- When minimum org hierarchy depth is 1, resource traversal aggregation strategies do not check if a resource is available in the root organization even for a resource requested for the root organization. This PR fixes this issue.
- https://github.com/wso2/product-is/issues/21214

Fix Root Org Template Resolving Edge Case

---

features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml

This PR updates the `organization management server feature` module to include the newly introduced `Resource Sharing Policy Management` component. This enhancement ensures the required dependency and bundle definition are added for seamless integration and functionality.
> This update ensures that the Resource Sharing Policy Management component is included in the server feature, enabling the system to manage resource-sharing policies effectively.
> - Add the necessary dependency for the Resource Sharing Policy Management component.
> - Define the bundle required for the component to function as part of the server feature.
> Added the dependency and bundle definition for the Resource Sharing Policy Management component in the Organization Management Server feature module.
---
[Introduce …

Introduce Dependency and Bundle Definition for Resource Sharing Policy Management

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListenerTest.java

- $subject
- Improvement for : https://github.com/wso2/product-is/issues/21208
- Improving the role deletion when the application is deleted from the sub organization (not shared apps).
- Please ensure that the PR [1] is merged before merging this PR since the kernel version bump is added to [1] which also needed for this PR as well.
[1] https://github.com/wso2-extensions/identity-organization-management/pull/409

Allow sub org level application deletion when the application is a sub org app

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListenerTest.java

Reverts wso2-extensions/identity-organization-management#409

Revert "Allow application creation in sub organization level"

---

components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/ResourceSharingPolicyHandlerService.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/ResourceSharingPolicyHandlerServiceImpl.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/constant/ResourceSharingSQLConstants.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/dao/ResourceSharingPolicyHandlerDAO.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/dao/ResourceSharingPolicyHandlerDAOImpl.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/test/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/ResourceSharingPolicyHandlerServiceImplTest.java

This PR introduces a new method to the `ResourceSharingPolicyHandlerService` interface for deleting resource-sharing policies of a specified resource type and ID within a given policy-holding organization. The method ensures proper permission checks for the initiating organization before deletion as well.
> TThis addition addresses the need to delete specific resource sharing policies within a specified policy-holding organization while validating permissions of the initiating organization. It resolves the following issues:
> - [Introduce a Centralized Resource Sharing Policy Management Service #21815](https://github.com/wso2/product-is/issues/21815)
> - Enable deletion of resource-sharing policies within a specified policy-holding organization.
> - Provide precise control by targeting …

Add Method to Delete Resource Sharing Policy in a Given Organization by Resource Type and ID

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingDataHolder.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingServiceComponent.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListener.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListenerTest.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/resources/testng.xml

Add doPostGetUserClaimValuesWithID, doPostGetUsersClaimValuesWithID and doPostGetUserClaimValueWithID methods to resolve the shared profiles based on SharedProfileValueResolvingMethod claim property in each claim property.
Part of https://github.com/wso2/product-is/issues/22126
Depends on 
- https://github.com/wso2-extensions/identity-organization-management/pull/426
- https://github.com/wso2/carbon-identity-framework/pull/6315

Add a listener to resolve shared profile based on SharedProfileValueResolvingMethod

---

components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/ResourceSharingPolicyHandlerService.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/ResourceSharingPolicyHandlerServiceImpl.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/constant/ResourceSharingSQLConstants.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/dao/ResourceSharingPolicyHandlerDAO.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/dao/ResourceSharingPolicyHandlerDAOImpl.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/exception/NotImplementedException.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/test/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/ResourceSharingPolicyHandlerServiceImplTest.java

This PR introduces mechanisms to clean up resource-sharing policies and shared attributes in the database when resources, attributes, or organizations are deleted. It ensures proper data integrity and consistency by removing orphaned entries.
> This feature resolves the need for proper cleanup mechanisms to remove resource-sharing policies and shared attributes when resources, attributes, or organizations are deleted. It resolves the following issues:
> - [Handle the Cleanup of Resource Sharing Policies and Attributes During Resource, Attribute, and Organization Deletion #22199](https://github.com/wso2/product-is/issues/22199)
> - Introduce SQL queries and methods for deleting resource-sharing policies and shared attributes by resource type, attribute type, or organization ID.
> - Ensure …

Handle the Cleanup of Resource Sharing Policies and Attributes During Resource, Attribute, and Organization Deletion.

---

components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/dao/ResourceSharingPolicyHandlerDAOImpl.java

> The current implementation for adding shared resource attributes lacked explicit batch queuing, leading to potential data inconsistencies during insert operations. This fix introduces proper batch insertion to ensure all attributes are processed correctly.
> - Ensure all shared resource attributes are queued for batch processing and insertion.
> - Maintain transactional integrity and improve reliability of the operation.
> - Prevent partial or incomplete batch execution scenarios.
> Introduced addBatch() within the batch processing logic to ensure each shared resource attribute is properly queued for insertion.
--
[Improve Batch Processing Logic for Adding Shared Resource Attributes #22430](https://github.com/wso2/product-is/issues/22430)

Add Batch Insert for Adding Shared Resource Attributes

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/SharingPolicyCleanUpHandler.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerDataHolder.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerServiceComponent.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/GovernanceConfigUpdateHandlerTest.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandlerTest.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/SharingPolicyCleanUpHandlerTest.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/resources/testng.xml

Resource sharing policies and the attached attributes for them will be stored in a generic data model.
Hence Resource types and Attributes types related data stored in above database table don't have foreignkey references.
For eg: If a user is deleted, the user sharing policies stored in the above tables need to be cleared through post event hadler / event listener of user delete action.
Similarly, we have to handle any supported resource type or attribute type.
Currently used **resources are Users**. Attaching to user sharing policies roles are used as attributes.
So, adding an event handler subscribed to POST_DELETE_ROLE_V2_EVENT and POST_USER_DELETE events. 
On organization deletion, clearing the resource policies will be handled due to foreign key restrictions.
Fix: …

Clear sharing policy store based on related resource deletion

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingDataHolder.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingServiceComponent.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/OrganizationUserSharingHandler.java

$subject.
this handler is responsible for sharing users to a newly created sub-organization based on the user sharing policies of it's ancestor organizations. 
- https://github.com/wso2/product-is/issues/22433

Add an event handler to share users to newly created organizations. 

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListener.java

> Currently, users who have been shared from a parent organization to a sub-organization can be deleted at the sub-organization level. This behavior is incorrect as shared users should only be removed (unshared) by the parent organization. This PR introduces a restriction to prevent unauthorized deletion of shared users.
> - Ensure that shared users cannot be deleted from the sub-organization level.
> - Restrict deletion unless the user's shared type is explicitly marked as "INVITED".
> - Enforce proper access control and validation in user sharing scenarios.
> Introduced a validation check to determine the user's sharing type before allowing deletion. If the user was shared through a method other than an invitation, deletion is restricted at the sub-organization level, ensuring only the …

Restrict Deletion of Shared Users at the Sub-Organization Level

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/SharedType.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/dao/OrganizationUserSharingDAOImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListener.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/models/UserAssociation.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/models/dos/ResponseOrgDetailsDO.java

> Enhance type safety by replacing String with the `SharedType` enum for sharedType in `UserAssociation` and `ResponseOrgDetailsDO`.
> - Ensure consistency in handling sharedType values.
> - Prevent invalid values by enforcing strict enum usage.
> - Facilitate safe conversions between database values and enums.
Modified `SharedType` to store explicit string values and provide `toString()` and `fromString()` methods.
Replaced `String sharedType` with `SharedType sharedType` in `UserAssociation` and `ResponseOrgDetailsDO`.
Ensured compatibility by handling case-insensitive mappings in `fromString()`.
Verified that database interactions correctly process the updated enum type.

Replace String with SharedType Enum in UserAssociation and ResponseOrgDetailsDO

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/dao/OrganizationUserSharingDAOImpl.java

> The issue prevented the deletion of a user who had been shared with a sub-organization, resulting in a `500 Internal Server Error`. The root cause was an invalid SharedType value being passed during the deletion process.
> Ensure the correct `SharedType` is retrieved and set when processing user associations to prevent errors during user deletion.
> Updated the retrieval mechanism for the `SharedType` to ensure the correct value is fetched dynamically rather than relying on a static reference. This prevents invalid values from causing failures during user deletion operations.
---
Related Issue:
[Unable to delete users from origin if the user is shared #22760](https://github.com/wso2/product-is/issues/22760)

Fix issue in retrieving and setting the correct SharedType for user associations

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java

- Ensure user associations are correctly classified by assigning `INVITED` for users added via sub-org invitations and `OWNER` for sub-org admins created during sub-org creation.
- Strengthen admin role integrity by preventing sub-org admins (`OWNER`) from being deleted within the sub-org.
- Establish a clear governance model where sub-org admins can only be removed via an unshare request from the parent organization.
- Assign `INVITED` type for users added via sub-org invitations.
- Assign `OWNER` type for sub-org admins created during sub-org creation.
- Restrict deletion of sub-org admins (`OWNER`) within the sub-org, allowing removal only via an unshare request from the parent organization.
- Update user association model to properly assign `INVITED` and `OWNER` types.
- Modify …

Assign INVITED and OWNER User Association Types & Enforce Sub-Org Admin Deletion Restriction

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImpl.java

> This PR fixes an issue where unsharing a user fails with an unauthorized deletion error, even when initiated from the correct organization. This regression was introduced after making the sharing process asynchronous.
> Ensure that unsharing a user works correctly by preserving the necessary thread-local context before executing the asynchronous operation.
> Captured and restored `IdentityUtil.threadLocalProperties` and relevant thread-local properties (`tenant name`, `username`, and `tenant ID`) before executing the unsharing logic asynchronously. This ensures the correct organizational context is maintained during execution.
---
[Unauthorized Deletion Error When Unsharing a User, Even When Initiated from the Correct Organization #22801](https://github.com/wso2/product-is/issues/22801)

Fix Unauthorized Deletion Error in User Unsharing Due to Missing Thread-Local Context

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java

User sharing is only supported for users who are managed by the sharing-initiated organization. Previously, attempts to share users not managed by the initiating organization caused failures, especially during new organization creation. This fix ensures that only eligible users are considered for sharing, preventing unnecessary errors.
- Enforce the rule that only users managed by the sharing-initiated organization can be shared.
- Prevent failures caused by attempting to share users outside the initiating organization.
- Improve system stability by skipping unsupported user-sharing scenarios.
- Added a validation to allow sharing only for users managed by the sharing-initiated organization.
- Skipped sharing for users outside the initiating organization.
- Logged a warning when a …

Skip user sharing for users who are not managed by the sharing-initiated organization

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
pom.xml

This PR implements the `doPostGetApplicationWithRequiredAttributes` method in the `FragmentApplicationMgtListener`. If the retrieving application is a shared app and if the main application is a discoverable application, inherit that to the shared application.
Dependent on
- https://github.com/wso2/carbon-identity-framework/pull/6462
- https://github.com/wso2/product-is/issues/22556

Inherit main application isDiscoverable property and access url to shared applications. 

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/OrganizationSessionHandler.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerDataHolder.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerServiceComponent.java
pom.xml

> Currently, when root organization session of a sub org user is terminated, sub organization session does not get terminated. With this PR, event handler is introduced to handle the sub organization session termination.
Related Issue - https://github.com/wso2/product-is/issues/22310

Handle org session termination when root session is terminated

---

components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/AttributeBasedOrganizationDiscoveryHandlerRegistry.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/OrganizationConfigManagerImpl.java
components/org.wso2.carbon.identity.organization.config.service/src/main/java/org/wso2/carbon/identity/organization/config/service/constant/OrganizationConfigConstants.java
components/org.wso2.carbon.identity.organization.config.service/src/test/java/org/wso2/carbon/identity/organization/config/service/AttributeBasedOrganizationDiscoveryHandlerRegistryTest.java
components/org.wso2.carbon.identity.organization.config.service/src/test/java/org/wso2/carbon/identity/organization/config/service/OrganizationConfigManagerImplTest.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/AttributeBasedOrganizationDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/internal/OrganizationDiscoveryServiceHolder.java

$subject
- https://github.com/wso2/product-is/issues/22285

Add support to register custom org discovery types

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingService.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/dao/OrganizationUserSharingDAO.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/dao/OrganizationUserSharingDAOImpl.java
pom.xml

Resolves the issue where a shared user was only retained in the last organization from the request payload, causing previous shared organizations to be removed.
Ensure that users remain shared across all specified organizations in the request payload by keeping track of organizations from the ongoing request.
Introduced a new mechanism to track organizations for which the user-sharing request has been initiated.
- Maintains a list (orgsInCurrentRequest) to track organizations in the current request.
- Filters out already processed organizations from previous requests to prevent unintended removals.
- Ensures user associations persist correctly across all requested organizations.
---
[Shared User Removed from Previously Selected Organizations in Selective User Sharing …

Fix Issue with Overwriting Previously Shared Organizations in Selective User Sharing

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingService.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/dao/OrganizationUserSharingDAO.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/dao/OrganizationUserSharingDAOImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserRoleGovernanceListener.java

Previously, the retrieval of non-deletable user role assignments did not consider domain-qualified usernames, leading to potential mismatches in multi-domain environments. This update ensures that role assignment checks are correctly performed by grouping usernames based on their respective domains.
- Accurately retrieve non-deletable user role assignments by considering domain-qualified usernames.
- Ensure domain-specific constraints are respected during query execution.
- Improve code maintainability by structuring queries per domain.
- Introduced logic to group usernames by domain before executing queries.
- Modified the query execution process to handle domain-separated usernames, ensuring accurate retrieval.
- Preserved existing functionality while enhancing support for multi-domain …

Support Domain-Qualified Usernames for Non-Deletable Role Assignments

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingService.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/dao/OrganizationUserSharingDAO.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/dao/OrganizationUserSharingDAOImpl.java
pom.xml

The existing implementation retrieves the full list of user-organization associations to check if an association exists. This approach is inefficient, particularly for large datasets, as it unnecessarily loads data instead of simply checking for existence.
This PR introduces an optimized SQL query using `EXISTS`, ensuring improved performance and compatibility across multiple database types.
- Improve query efficiency by replacing the full association retrieval with an `EXISTS` check.
- Ensure compatibility with all required database types: H2, IBM DB2, MSSQL, MySQL, MySQL Cluster, Oracle, Oracle RAC, and PostgreSQL.
- Centralize query selection logic in `OrganizationUserSharingDAOImpl` for easier maintainability and scalability.
- Replaced fetching a full list of associations with a …

Improve Organization-User Association Check for Performance and Ensure Multi-DB Compatibility

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java

The `rolesRef` field in the response of the Shared Users GET API (`/users/{userId}/shared-organizations`) currently includes unnecessary query parameters (`&after=&before=&limit=&filter=&recursive`). This PR removes these redundant parameters to improve API response clarity.
- Ensure the `rolesRef` field only contains the base URL without unnecessary query parameters.
- Provide a cleaner and more intuitive API response.
- Updated the API response logic to exclude unnecessary query parameters from `rolesRef`.
- Verified the new response format.

Remove Unnecessary Query Parameters from rolesRef in Shared Users GET API Response

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandler.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandlerTest.java

Fixes: https://github.com/wso2/product-is/issues/22061
The following goals are achieved through this fix:
- The claim properties get propagated during the organization's creation.
- The attribute mapping name for the **PRIMARY** user store gets propagated during the organization's creation.
- The attribute mapping names for the other user stores are not inherited.
- The **ExcludedUserStores** is excluded when inheriting the properties.
- The custom local claims are not inherited.
**IMPORTANT**: This approach is slightly rudimentary, as any changes in the claim properties and attribute mappings would update the local claim in the database.
Let the OrgClaimMgtHandler subscribe to the POST_ADD_ORGANIZATION event, and handle the claim propagation accordingly.

Inherit local claim properties and attribute mappings during organization creation

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListener.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListenerTest.java

Ensure that the shared type claim is returned in user profile responses by updating the `SharedUserOperationEventListener`.
- Dynamically populate the shared type value when retrieving user claims.
- Set the default value for old shared users as `INVITED`.
- Ensure that the claim is correctly populated in all relevant user retrieval methods.
- Updated `doPostGetUserClaimValuesWithID`, `doPostGetUsersClaimValuesWithID`, and `doPostGetUserClaimValueWithID` to set the sharedType claim dynamically.
- Introduced `setRuntimeClaims(claimMap, Collections.singleton(CLAIM_USER_SHARED_TYPE), userAssociation)` to resolve the shared type from user associations.
- Implemented `getClaimBasedOnSharedType()` to determine the shared type from userAssociation, defaulting to `INVITED` for older shared users. …

[Claim] Return Shared Type Claim in User Profile Responses

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

$subject
Related PRs: https://github.com/wso2-extensions/identity-organization-management/pull/478
Related Issues:: https://github.com/wso2/product-is/issues/23085
The Warn Log:
The Audit Log:
```
TID: [-1234] [2025-02-17 23:49:50,456] [009775cb-b626-4a29-b32e-54958186be5d]  WARN {AUDIT_LOG} -
{"id":"5514df35-95ad-45b2-8f2f-90e97e8f3980","recordedAt":"2025-02-17T18:19:50.452509Z",
"requestId":"009775cb-b626-4a29-b32e-54958186be5d","initiatorId":"aad2f0aa-d22f-4db5-9286-50060af0495e",
"initiatorType":"User","targetId":"pickup","targetType":"Application","action":"update-application",
"data":{"sharedTenantDomain":"46487945-eb2a-476b-8914-28609ef57fd9","parentAppName":"pickup",
"conflictingAppId":"67ae6c28-c9d5-4e37-8d4c-333e0378a215","conflictingAppName":"pickup", …
```

Add missing dependencies for AuditLogBuilder in OSGi imports

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListenerTest.java

$subject
Fixes: https://github.com/wso2/product-is/issues/23239
Currently, modification of application names for sub-org-managed applications is restricted. This PR allows the modification of sub-org-managed applications.
**Tested outflows:**
- Root app name update allowed. It's shared app's name should be updated
- Invoke app name update call for sub org's shared app via REST API -> This should be blocked
- Invoke sub org own app's name update patch call -> This should allowed

Allow application name modification for sub org managed applications

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java

Currently, when unsharing a user from a selective organization or a set of organizations, if the provided `userId` or `organizationId` is invalid (i.e., the user or organization does not exist), the server throws a `NullPointerException`.
**Expected behavior:** The API should skip invalid IDs and proceed with valid ones.
- Prevent the API from failing with an NPE when encountering an invalid `userId` or `organizationId`.
- Ensure the API skips invalid entries and processes only valid user-organization mappings.
- Added a null check for userAssociation before attempting to access its properties (`userId`, `organizationId`).
- This prevents potential NullPointerExceptions when the method is called with a `null` value.
- The rest of the logic remains unchanged, ensuring the method continues …

Fix NPE when Unsharing a User with Invalid User ID or Organization ID

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListenerTest.java

$subject
Fixes: https://github.com/wso2-enterprise/asgardeo-product/issues/29230
Instead of the server error, this error is now thrown:

Restrict fragment application deletion by resource ID

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImpl.java

Currently, in the User Sharing API, while the API accepts any case format for the `audience.type` field, the backend performs a case-sensitive comparison. This results in roles not being assigned if the audience type is not provided in lowercase.
This PR resolves this issue by ensuring that the backend performs a case-insensitive comparison, allowing roles to be assigned correctly regardless of how the `audience.type` value is formatted.
- Ensure that role assignments work correctly irrespective of the capitalization of `audience.type`.
- Improve API usability by aligning backend behavior with the API's flexibility in accepting any case format.
- Updated the backend logic to compare the `audience.type` field in a case-insensitive manner.
---
[User Sharing API Should Support …

Make Role Audience Type Comparison Case-Insensitive in User Sharing API

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImplTest.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/TestUserSharingConstants.java
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/test/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/ResourceSharingPolicyHandlerServiceImplTest.java

The User Sharing Component currently lacks unit test coverage, which affects its reliability and maintainability. This PR introduces unit tests to validate key functionalities and ensure expected behavior under different conditions.
- Improve test coverage for the User Sharing Component.
- Ensure correctness by validating core functionalities.
- Enhance maintainability and prevent regressions in future updates.
- Add unit tests covering various use cases, including validation logic and business rules.
- Ensure test cases handle both expected and edge cases.
- Follow best practices for structuring unit tests to maintain readability and maintainability.

Add Unit Tests for User Sharing Component

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/OrganizationSessionHandler.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/OrganizationSessionHandlerTest.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/resources/testng.xml

- This PR adds supports to extend the underlying sub organization sessions when the root organization session is extended with the session extension API.
- https://github.com/wso2/product-is/issues/23291

Extend sub organization user sessions While using Session Extension API for root organization

---

components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/AttributeBasedOrganizationDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManager.java
components/org.wso2.carbon.identity.organization.discovery.service/src/test/java/org.wso2.carbon.identity.organization.discovery.service/OrganizationDiscoveryManagerImplTest.java

Adds an overloaded method to the OrganizationDiscoveryManager and AttributeBasedOrganizationDiscoveryHandler interfaces to include the authentication context during organization discovery.
- https://github.com/wso2/product-is/issues/23390
- https://github.com/wso2-extensions/identity-auth-organization-login/pull/55

Add overloaded method to include authentication context during organization discovery

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/OrganizationSessionHandler.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/OrganizationSessionHandlerTest.java

> Currently when the sub org user selects remember me option, only sub org session is set as remember me true. We need to update the root org session similarly to avoid idle session timeouts.
Issue - https://github.com/wso2/product-is/issues/23550

Handle remember me option of root org session to align with sub org session

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

To ensure that the organization switch option is available when an organization is created using the API with a user token.
- Align behavior of org creation via Console, Basic Auth, and user-token-based API.
- Prevent missing switch option in Console for user-token-created organizations.
- Ensure that the Console Administrator role is assigned only when appropriate.
- Whether the user already has the Administrator role scoped to the Console application.
- Whether the request is authenticated via Basic Auth.
- Whether the user is authenticated through the Console application.
- Introduced `isConsoleAdministratorAssignmentAllowed(...)` to verify if the Console Administrator role can be assigned.
- Allows assignment if:
- The user already has a Console app audience role.
- Request is …

Fix Missing Organization Switch Option for API-Created Orgs via User Token

---

components/org.wso2.carbon.identity.organization.management.claim.provider/pom.xml
components/org.wso2.carbon.identity.organization.management.claim.provider/src/main/java/org/wso2/carbon/identity/organization/management/claim/provider/OrganizationClaimProvider.java
components/org.wso2.carbon.identity.organization.management.claim.provider/src/test/java/org/wso2/carbon/identity/organization/management/claim/provider/OrganizationClaimProviderTest.java
components/org.wso2.carbon.identity.organization.management.claim.provider/src/test/resources/testng.xml

$subject
This update will add organization handle to JWT access tokens and id tokens
Send as an additional claim along with _org_name_ and _org_id_
**Access tokens**
- Super ORG
- Sub Org with handle
- Sub Org without handle (only ID)
**ID tokens**
- Super ORG
- Sub Org with handle
- Sub Org without handle (only ID)
- https://github.com/wso2/product-is/issues/23526

Add organization handle to JWT access tokens and id tokens

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandler.java
pom.xml

Currently, the addSharedApplicationsToOrganization method in the sub organization creation flow retrieves all the applications of the parent organization regardless of whether they are marked to be shared. When there are a large number of applications, this leads to a large number of DB calls which leads to a significant increase in the time taken.
The objective of the above logic is to share the applications which have the "shareWithAllChildren" property with the newly created sub organization. In order to do that, we are retrieving all the applications and then checking which of them has the above property set to true. This causes an unnecessary overhead as it is not required to retrieve all applications and iterate through them.
- https://github.com/wso2/product-is/issues/24339
This …

Improve the app retrieval logic when adding shared apps to organization during org creation

---

components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryHandlerImpl.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/constant/DiscoveryConstants.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/internal/OrganizationDiscoveryServiceComponent.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/internal/OrganizationDiscoveryServiceHolder.java
components/org.wso2.carbon.identity.organization.discovery.service/src/test/java/org.wso2.carbon.identity.organization.discovery.service/OrganizationDiscoveryHandlerImplTest.java
components/org.wso2.carbon.identity.organization.discovery.service/src/test/resources/testng.xml
pom.xml

> This PR introduces organization discovery handler implementation to discover organization based on provided discovery parameters.
Related PRs - https://github.com/wso2/carbon-identity-framework/pull/6890
Issue - https://github.com/wso2/product-is/issues/24454

Add Organization Discovery Handler Implementation

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

$subject
With this fix, it will make sure that only the apps that previously shared with all organizations will have the `ALL` Role Mode. All other role modes will be handle with previously added new role sharing backend

Modify the sharingMode return for org shared applications types

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerServiceComponent.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/ResidentIdPMgtListener.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/ResidentIdPMgtListenerTest.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/resources/testng.xml
pom.xml

Password expiry rules related to roles are stored in the format: `1,30,roles,eq,<ROLE-ID>`
When these roles are inherited, corresponding shared role Ids should be resolved based on wether they are shared to the sub-organization or not.
- https://github.com/wso2/carbon-identity-framework/pull/7050
- https://github.com/wso2/product-is/issues/24904

Add listener to resolve shared role Ids of password expiry rules

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Shared application is set to inherit the parent application version.
Related issue : https://github.com/wso2/product-is/issues/25354

Inherit parent application version

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImplTest.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImplTest.java

Fic for https://github.com/wso2/product-is/issues/25347
This pull request refactors how organization IDs are resolved and used throughout the application management codebase, replacing direct usage of tenant domains with organization IDs for discoverable shared application queries. It also updates error messages and test cases to align with these changes, improving consistency and correctness in organization context handling.
**Core logic changes:**
* Updated `OrgApplicationManagerImpl.java` methods to resolve organization IDs from tenant domains before fetching root organization IDs, ensuring queries operate in the correct organization context. [[1]](diffhunk://#diff-6643b27201b8eee5beea7c151b17a82fc3ff7108d93f452041881197c0542b61L2143-R2144) …

[Next] Resolve sub org level discoverable app view issue in myaccount when org id and org handle are different

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImplTest.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImplTest.java

Fix for https://github.com/wso2/product-is/issues/25347
This pull request refactors how organization IDs are resolved and used throughout the application management codebase, replacing direct usage of tenant domains with organization IDs for discoverable shared application queries. It also updates error messages and test cases to align with these changes, improving consistency and correctness in organization context handling.
**Core logic changes:**
* Updated `OrgApplicationManagerImpl.java` methods to resolve organization IDs from tenant domains before fetching root organization IDs, ensuring queries operate in the correct organization context. [[1]](diffhunk://#diff-6643b27201b8eee5beea7c151b17a82fc3ff7108d93f452041881197c0542b61L2143-R2144) …

Resolve sub org level discoverable app view issue in myaccount when org id and org handle are different
