wso2-extensions/identity-organization-management

README.md
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/constant/AuthorizationConstants.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/dao/OrganizationManagementAuthzDAOImpl.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/util/OrganizationManagementAuthzUtil.java
components/org.wso2.carbon.identity.organization.management.authz.valve/src/main/java/org/wso2/carbon/identity/organization/management/authz/valve/OrganizationManagementAuthzValve.java
components/org.wso2.carbon.identity.organization.management.endpoint/pom.xml
components/org.wso2.carbon.identity.organization.management.role.mgt.core/src/main/java/org/wso2/carbon/identity/organization/management/role/mgt/core/dao/OrganizationUserRoleMgtDAOImpl.java
components/org.wso2.carbon.identity.organization.management.role.mgt.core/src/main/java/org/wso2/carbon/identity/organization/management/role/mgt/core/util/Utils.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
pom.xml

1. Minor fixes mentioned in CR.
2. Added auth fixes.

Auth feature fixes and CR fixes.

---

components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/constant/AuthorizationConstants.java
components/org.wso2.carbon.identity.organization.management.authz.valve/src/main/java/org/wso2/carbon/identity/organization/management/authz/valve/OrganizationManagementAuthzValve.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java

Adding role-management module to organization management.

Role Management Module Fixes

---

components/org.wso2.carbon.identity.organization.management.role.mgt.core/src/main/java/org/wso2/carbon/identity/organization/management/role/mgt/core/constants/DatabaseConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> Amend SQL queries to be compatible with H2 and MySQL
> Add Parent Id as filter parameter for Org List API

MySQL compatibility and add ParentId to org filter

---

components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/OrganizationsApi.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/resources/org.wso2.carbon.identity.organization.management.yaml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CachedBackedOrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
pom.xml

This PR updates the status of the tenant representing the tenant type organization in the UM_TENANT table based on:
- deleting an organization (tenant will be disabled)
- updating the status of an organization

Add improvements to tenant type organization

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/Organization.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/ParentOrganizationDO.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImplTest.java

Remove UM_TENANT_ID from UM_ORG

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAO.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java

Remove tenant id from UM_ORG_ROLE

---

pom.xml

Bump kernel version to 4.7.0-beta5

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/CarbonContextCreatorValve.java
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/internal/OrganizationManagementTomcatDataHolder.java
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/internal/OrganizationManagementTomcatServiceComponent.java
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/util/Util.java
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Issue: https://github.com/wso2/product-is/issues/13953

Add organization routing specific carbon context creator valve

---

components/org.wso2.carbon.identity.organization.management.role.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/role/management/endpoint/model/RoleGetResponseGroup.java
components/org.wso2.carbon.identity.organization.management.role.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/role/management/endpoint/model/RoleGetResponseUser.java
components/org.wso2.carbon.identity.organization.management.role.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/role/management/endpoint/model/RoleObjMeta.java
components/org.wso2.carbon.identity.organization.management.role.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/role/management/endpoint/model/RolePutResponseMeta.java
components/org.wso2.carbon.identity.organization.management.role.management.endpoint/src/main/resources/org.wso2.carbon.identity.organization.management.role.management.yaml

Change role management endpoint path to have organization domain instead of tenant domain

---

components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/dao/OrganizationManagementAuthzDAOImpl.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/handler/OrganizationManagementAuthzHandler.java
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

- Check  the user is authorized using the new authorization model
- Remove organization level authz valve (removed only from feature)

Handle authorization in organization level

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.authn/src/main/java/org/wso2/carbon/identity/organization/management/application/authn/EnterpriseIDPAuthenticator.java

Handle tenant resolution for ROOT org when login to the application shared by the ROOT organization.

Handle tenant resolution for ROOT org in application login

---

components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/constants/OrganizationManagementEndpointConstants.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/util/OrganizationManagementEndpointUtil.java
components/org.wso2.carbon.identity.organization.management.role.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/role/management/endpoint/constant/RoleManagementEndpointConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

The org mgt endpoint is packed inside the api war and hence the below provided path should be changed to match the new URI path

Change URI paths

---

components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/dao/OrganizationManagementAuthzDAOImpl.java

Depends on https://github.com/wso2/product-is/issues/14067

Add authorization to group members

---

components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/OrganizationManagementAuthorizationManager.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/constant/AuthorizationConstants.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/dao/OrganizationManagementAuthzDAO.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/dao/OrganizationManagementAuthzDAOImpl.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/handler/OrganizationManagementAuthzHandler.java

Fixes https://github.com/wso2-extensions/identity-organization-management/issues/73

Fix organization level authz for org-role assigned for root org

---

components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/service/OrganizationManagementService.java

Add recursive query param for URLs build for cursor based pagination

---

components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/dao/OrganizationManagementAuthzDAOImpl.java

Temporary Fix for https://github.com/wso2/product-is/issues/14106 
Future, there could be different types of groups apart from userstore groups (eg: entire organizations, groups with collaborators etc). Then user belonged groups should be checked accordingly.

Fix internal server error during group authorizing

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Fix https://github.com/wso2/product-is/issues/14181

Not allow to delete or disable root organization

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java

Part of fix: https://github.com/wso2/product-is/issues/14154

Get ancestor list for a given org

---

components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/OrganizationsApi.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/OrganizationsApiService.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/GetOrganizationResponse.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/impl/OrganizationsApiServiceImpl.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/java/org/wso2/carbon/identity/organization/management/endpoint/service/OrganizationManagementService.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/resources/org.wso2.carbon.identity.organization.management.yaml

Resolves https://github.com/wso2/product-is/issues/14194

Remove showChildren in fetch organization by id API request

---

components/org.wso2.carbon.identity.organization.management.endpoint/src/gen/java/org/wso2/carbon/identity/organization/management/endpoint/model/OrganizationPOSTRequest.java
components/org.wso2.carbon.identity.organization.management.endpoint/src/main/resources/org.wso2.carbon.identity.organization.management.yaml

Resolves https://github.com/wso2/product-is/issues/14168

Make the default organization type as tenant

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverService.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java

> Allow resolving of user by user ID

Add user resolve using userId

---

components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/OrganizationSwitchGrant.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/OrganizationSwitchGrantValidator.java
components/org.wso2.carbon.identity.organization.management.oauth2.grant/src/main/java/org/wso2/carbon/identity/organization/management/oauth2/grant/util/OrganizationSwitchGrantConstants.java
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Add organization switching grant type to organization feature

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.authn/pom.xml
components/org.wso2.carbon.identity.organization.management.authn/src/main/java/org/wso2/carbon/identity/organization/management/authn/OrganizationAuthenticator.java
components/org.wso2.carbon.identity.organization.management.authn/src/main/java/org/wso2/carbon/identity/organization/management/authn/constant/AuthenticatorConstants.java
components/org.wso2.carbon.identity.organization.management.authn/src/main/java/org/wso2/carbon/identity/organization/management/authn/internal/AuthenticatorDataHolder.java
components/org.wso2.carbon.identity.organization.management.authn/src/main/java/org/wso2/carbon/identity/organization/management/authn/internal/AuthenticatorServiceComponent.java
components/org.wso2.carbon.identity.organization.management.authn/src/test/java/org/wso2/carbon/identity/organization/management/authn/OrganizationAuthenticatorTest.java
components/org.wso2.carbon.identity.organization.management.authn/src/test/resources/testng.xml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Rename organization authenticator.

Rename organization authenticator.

---

components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/Constants.java
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/listeners/TenantAssociationManagementListener.java

Add minimum permission for org-creator

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java

Resolves https://github.com/wso2/product-is/issues/14265

Block cross tenant flow for creating an immediate child of root org

---

components/org.wso2.carbon.identity.organization.management.role.management.endpoint/pom.xml
pom.xml

Issue: https://github.com/wso2/product-is/issues/14129

Update maven-compiler-plugin version and set parameters to true

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagementInitialize.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagementInitializeInstance.java

Add an interface to check organization management initialize instance

---

components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/Constants.java
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/listeners/TenantAssociationManagementListener.java

Add user mgt create permission to organization creator

---

components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/CarbonContextCreatorValve.java
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/internal/OrganizationManagementTomcatDataHolder.java
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/internal/OrganizationManagementTomcatServiceComponent.java

Expose o/ path only if organization mgt is enabled

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> Rename fragment app to have same name as original application.

Rename fragment application name to original application.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverService.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Related to https://github.com/wso2/product-is/issues/14480

Add method to resolve user's root organization

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtDataHolder.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtServiceComponent.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
pom.xml

> PR has the implementation to add Organization Login IDP to the application SignIn Methods when the application is shared.

Add Organization Login IDP at the application share request.

---

pom.xml

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Change version range of scim2

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Bump kernel version to 4.7.0

---

pom.xml

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Increase oauth version range

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java

> $subject
https://github.com/wso2/product-is/issues/14381
https://github.com/wso2-extensions/identity-organization-management/issues/60

Fix for displaying tenant created user as null when organization creation

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/OrganizationManagementAuthorizationManager.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/constant/AuthorizationConstants.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/dao/OrganizationManagementAuthzDAO.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/dao/OrganizationManagementAuthzDAOImpl.java
components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/handler/OrganizationManagementAuthzHandler.java
components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Reverts wso2-extensions/identity-organization-management#134

Revert "Move org mgt service module to org mgt core"

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> Skip login consent in fragment application.

Skip consent in fragment application.

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> $subject
https://github.com/wso2/product-is/issues/14217

Restrict super organization level role management

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Fixes https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/21

Allow deletion of fragment application when stop sharing the app.

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java

Improve authorization logic considering accessed organization resource

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
pom.xml

$subject
https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/30

Add application share and fragment app access service level validation

---

components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/CarbonContextCreatorValve.java

> $subject
- https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/77

Retry tenant domain resolve when NPE for verify first organization qualified request

---

components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/listeners/TenantAssociationManagementListener.java
pom.xml

part of fix Fix https://github.com/wso2/product-is/issues/14001

Store tenant creator id in realm when creation tenants by organization creation

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
pom.xml

part of fix Fix https://github.com/wso2/product-is/issues/14001

Resolve admin username of org related tenants after realm storing user id separately

---

components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/src/main/java/org/wso2/carbon/identity/organization/management/tomcat/ext/tenant/resolver/CarbonContextCreatorValve.java

Reverts wso2-extensions/identity-organization-management#152

Revert "Retry tenant domain resolve when NPE for verify first organization qualified request"

---

components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/src/main/java/org/wso2/carbon/identity/organization/management/tenant/association/listeners/TenantAssociationManagementListener.java
pom.xml

Skip organization role based - organization to user association,if org uses carbon roles

---

components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
pom.xml

Remove unwanted scim and charon dependencies and imports from the organization role management component

Remove unwanted scim and charon dependencies and imports

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtDataHolder.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtServiceComponent.java
pom.xml

Add federated_org oidc claim and configure SaaS app claims

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Remove runtime claims sharing to sub orgs

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Update fragment app listener to return local subject id config from main app.

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java

Update user organization claim

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Fix fragment application deletion when main application is deleted

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

- Refactoring the pom versions to match with the branch.

[1.2.x] Refactoring pom Versions

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java

> $subject
> Fix error prompted when creating an organization (PostgreSQL DB).

Use integer type for app id placeholder with prepare statement

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java
pom.xml

Fix org role patch remove operation with no filter expression

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java

> $subject
> * https://github.com/wso2-enterprise/asgardeo-product/issues/13023

Avoid adding attributes for patch replace operation with empty value

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtDataHolder.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/RoleManagerImpl.java

Add method comments

---

components/org.wso2.carbon.identity.organization.management.ext/src/main/java/org/wso2/carbon/identity/organization/management/ext/OrganizationManagerListenerImpl.java

Handle client errors of event handlers

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

$Subject
Adding basic auth as the auth step of newly created service providers(if authType is default) from applicationDAO impl https://github.com/wso2/carbon-identity-framework/blob/1af4a74dd037db03ea4ccee44fb2b78e84289d3c/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java#L2754 cause for behavioural changes. There could be customizations to add the basic auth from listeners. Therefore, we are fixing this issue at the application sharing point

Fix issue of not showing basic authenticator once application is shared

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
pom.xml

$subject
Depends on 
- https://github.com/wso2/carbon-identity-framework/pull/4372
- https://github.com/wso2-extensions/identity-organization-management-core/pull/48
- https://github.com/wso2-enterprise/asgardeo-deployment-helm-is/pull/619

Set callback URL of fragment apps to app owner org's commonauth endpoint

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/model/MainApplicationDO.java

> Addressed the following comments
> * https://github.com/wso2-extensions/identity-organization-management/pull/145#discussion_r1088717014
> * https://github.com/wso2-extensions/identity-organization-management/pull/145#discussion_r1088717351
> * https://github.com/wso2-extensions/identity-organization-management/pull/145

Added doc comments for public methods

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Add identity provider client error handler when sharing applications

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

This PR addresses the commenting issues mentioned in the following git comments.
- https://github.com/wso2-extensions/identity-organization-management/pull/154/files#r1065384288
- https://github.com/wso2-extensions/identity-organization-management/pull/154/files#r1065385285

Improve comments related to application sharing

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Set local claim dialect true for organization login IDP

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java

Fix role patch operation issue

---

components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAO.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/internal/RoleManagementServiceComponent.java
components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/listener/OrganizationUserOperationEventListener.java
pom.xml

Add user operation event listener for remove user role assignments on user deletion events

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java

> $Subject
> Update permissions and groups of a role in local Asgardeo setup

Fix role patch operation issue for groups and permissions.

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManager.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Add new service to resolve shared application based on main app uuid

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Add the application roles claim as the requested claim for the fragmented app even though its not requested from the parent application

Add application roles claim to B2B fragment app's filtered claims

---

components/org.wso2.carbon.identity.organization.management.role.management.service/src/main/java/org/wso2/carbon/identity/organization/management/role/management/service/dao/RoleManagementDAOImpl.java

>  During transaction operations, not being some operations being transactional cause this issue.
- https://github.com/wso2-extensions/identity-organization-management/pull/196

Fix suborganization creation issue due to table lock in mssql server

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml

Bump version on pom.xml

---

features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

> Add handler component as a feature

Add handler to features

---

pom.xml

Update governance version range.xml

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/GovernanceConfigUpdateHandler.java

> Since the static map had an initialization issue change it.

Change the configurationDetails map initialization

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
pom.xml

Check application role support is enabled before using application role claim

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
pom.xml

> $subject
- https://github.com/wso2-extensions/identity-organization-management-core/pull/69

Block shared application sharing and fix app sharing issue when b2b apps in super org in IDaaS deployments.

---

components/org.wso2.carbon.identity.organization.management.claim.provider/pom.xml
components/org.wso2.carbon.identity.organization.management.claim.provider/src/main/java/org/wso2/carbon/identity/organization/management/claim/provider/OrganizationClaimProvider.java
components/org.wso2.carbon.identity.organization.management.claim.provider/src/main/java/org/wso2/carbon/identity/organization/management/claim/provider/internal/OrganizationClaimProviderServiceComponent.java
components/org.wso2.carbon.identity.organization.management.claim.provider/src/main/java/org/wso2/carbon/identity/organization/management/claim/provider/internal/OrganizationClaimProviderServiceComponentHolder.java
components/org.wso2.carbon.identity.organization.management.governance.connector/pom.xml
components/org.wso2.carbon.identity.organization.management.governance.connector/src/main/java/org/wso2/carbon/identity/organization/management/governance/connector/OrganizationMgtGovernanceConnectorImp.java
components/org.wso2.carbon.identity.organization.management.governance.connector/src/main/java/org/wso2/carbon/identity/organization/management/governance/connector/internal/OrganizationMgtGovernanceConnectorService.java
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

> The claim provider and governance connector is moved to this repository

Add claim provider and governance connector

---

pom.xml

Fix build issue

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Improve exception handling of pre-create application listener

---

components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreService.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/dao/UserInvitationDAO.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/dao/UserInvitationDAOImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/exception/UserInvitationMgtClientException.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/exception/UserInvitationMgtException.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/exception/UserInvitationMgtServerException.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/handler/UserInvitationEventHandler.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/internal/UserInvitationMgtDataHolder.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/internal/UserInvitationMgtServiceComponent.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/models/Invitation.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/models/RoleAssignments.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/role/LocalRoleManagerService.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/role/RemoteRoleManagerServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/role/RoleManagerService.java
pom.xml

> Indroducing the capability to manage the invitations which will trigger to the organization user sharing. 
> Facilitate the core service for the invitation management.

Add organization user invitation management core service

---

features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Add organization user invitation management jar to the distribution

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/listener/OrgSharedUserOperationEventListener.java

Disable the shared user op event listener

---

components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/handler/UserInvitationEventHandler.java

* $subject to provide the capability to enable or disable the event handler through the configuration.

Add support to enable/disable the event handler

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/handler/UserInvitationEventHandler.java

Improve configuration handling in the invitation event handler

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java

* $subject
* https://github.com/wso2/carbon-identity-framework/pull/4912

Update managed org claim to an identity claim

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/listener/OrgSharedUserOperationEventListener.java

* $subject
* Added `doPreSetUserClaimValueWithID` listener method.
* Improve `doPreSetUserClaimValuesWithID` listener method.
* Minor improvements

Improve shared user operation event listener

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/dao/UserInvitationDAOImpl.java

* Improve association extraction from the associations table.

Improve association extraction for organization users

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandler.java

Fix issue 
- https://github.com/wso2/product-is/issues/16914

fix issues in custom external attribute creation on sub-orgs

---

components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/AttributeBasedOrganizationDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/EmailDomainBasedDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManager.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManagerImpl.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/dao/OrganizationDiscoveryDAO.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/dao/OrganizationDiscoveryDAOImpl.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/internal/OrganizationDiscoveryServiceHolder.java
pom.xml

Issue https://github.com/wso2/product-is/issues/16728

Add new functionalities to organization discovery service

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> When shared app is required to delete, a tenant flow corresponds to that shared app's organization should be started as the operation is executed on a resource in a different tenant.
- https://github.com/wso2/product-is/issues/17081

Start organization specific tenant flow when shared app is deleted

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/resources/META-INF/component.xml

Add permissions for organization user invitation

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtDataHolder.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtServiceComponent.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
pom.xml

Part of https://github.com/wso2/product-is/issues/16363

Resolve associated roles of shared app

---

components/org.wso2.carbon.identity.organization.management.governance.connector/src/main/java/org/wso2/carbon/identity/organization/management/governance/connector/OrganizationMgtGovernanceConnectorImp.java

$subject
Address https://github.com/wso2/product-is/issues/17169

Update friendly name of the connector config

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandler.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
pom.xml

Implement listeners to resolve associated role details of shared app

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> With the [improvements](https://github.com/wso2/product-is/issues/16365) made for tokens issued for B2B apps, the following fields are available.
org_id, org_name, user_org
Previously, the user_organization OIDC claim was registered due to the initial token retrieved for B2B apps did not conatined the organization information of the b2b user. But as per above image, the user_org claim includes the user's org information and the org_id includes the organization the token is issued to. Hence by this PR remove the OIDC claim creation.
- https://github.com/wso2/product-is/issues/16365
The newly introduced `user_org` claim is supposed to break the existing B2B apps which uses the `user_organization` claim for some administrative tasks. The reason for having different name is to comply with …

Stop registering user_organization OIDC claim

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

Fix associated user org id resolving issue

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java

Readds constant removed from https://github.com/wso2-extensions/identity-organization-management/pull/252/files#diff-405d67365bab210891a47742ff318ba0c34104c08b2ecab2f8ed79b2416b27f6L117

Add removed public constant

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Fix sharing issue in localAndOutboundAuthenticationConfig

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

$subject
- https://github.com/wso2/product-is/issues/17499

Fix shared oauth_consumer_apps delete issue while deleting main application

---

components/org.wso2.carbon.identity.organization.management.claim.provider/src/main/java/org/wso2/carbon/identity/organization/management/claim/provider/OrganizationClaimProvider.java

Reverts wso2-extensions/identity-organization-management#285

Revert "Stop adding org_id to the ID token/JWT Access token for B2C logins"

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/util/OrganizationSharedUserUtil.java

Part of https://github.com/wso2-extensions/identity-organization-management/pull/288

Improve debug logs

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingDataHolder.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingServiceComponent.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

Fix user sharing in legacy runtime

---

components/org.wso2.carbon.identity.organization.management.governance.connector/src/main/java/org/wso2/carbon/identity/organization/management/governance/connector/OrganizationMgtGovernanceConnectorImp.java

Change the organization onboarding self service configs according to new terminology
Related Issue
- https://github.com/wso2/product-is/issues/17616

Change the organization onboarding self service configs according to new terminology

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

> Prevent user sharing happening in the legacy runtime

Remove user sharing in legacy runtime

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandler.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/util/OrgApplicationManagerUtil.java
pom.xml

Issue: https://github.com/wso2/product-is/issues/17510

Add SP property to persist if the SP is shared with sub orgs

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingDataHolder.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/internal/OrganizationUserSharingServiceComponent.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

> Fixed https://github.com/wso2/product-is/issues/17459 …

Introduce Administrator role for Console with application audiance.

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

This will fix the following issues
- https://github.com/wso2/product-is/issues/17838
- https://github.com/wso2/product-is/issues/17725
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …

Fix callback URL resolving for shared application

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/util/OrgApplicationManagerUtil.java

Issue: https://github.com/wso2/product-is/issues/17518

Handle add and removal of org sso authenticator during app update

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandler.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

$Subject
- https://github.com/wso2/product-is/issues/17732

Fix username being null in carbon context for event handlers hit on org creation flow

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Stop adding organization SSO IDP for the console when application sharing

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/GovernanceConfigUpdateHandler.java

>  [Add sub-organization account recover capability](https://github.com/wso2-extensions/identity-organization-management/pull/205)

Addressing the review comments

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/util/OrgApplicationManagerUtil.java

>  $subject
- https://github.com/wso2/product-is/issues/17943

Add organization SSO IDP URL

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java
pom.xml

Issue: https://github.com/wso2/product-is/issues/17908

Fix postgres error with adding new org

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/GovernanceConfigUpdateHandler.java

$subject
https://github.com/wso2/product-is/issues/17946

Enable "invite the user to set the password" option in Sub Organizations by default

---

components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/constant/UserInvitationMgtConstants.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/test/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImplTest.java

Resolve : https://github.com/wso2/product-is/issues/17937 …

Validate whether the given role list contains the console access

---

components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/dao/OrganizationDiscoveryDAOImpl.java

> $subject
> * https://github.com/wso2/product-is/issues/18079

Added oracle support for getDiscoveryOrganizationIds query

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java

> Start tenant flow before creating shared role with Org audience
- https://github.com/wso2/product-is/issues/18460

Start tenant flow before creating shared role with Org audience

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Enable org admin login to Console

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerDataHolder.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerServiceComponent.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
pom.xml

> 
- https://github.com/wso2/product-is/issues/18390

Fix system & everyone role deletion issue

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/SQLConstants.java

$subject
- https://github.com/wso2/product-is/issues/18551

Fix DB queries to support oracle

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java

Issue https://github.com/wso2/product-is/issues/18695

Fix internal server error when inviting to non existing parent user

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java

Resolve https://github.com/wso2/product-is/issues/18695 …

Handle the null pointer exception when user is not exist in parent organization

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java

Reverts wso2-extensions/identity-organization-management#324

Revert "Handle the null pointer exception when user is not exist in parent organization"

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> $subject
- https://github.com/wso2/product-is/issues/18751

Fix super tenant organization SSO user logout issue

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandler.java

> Fix sub org claim updates when onboarding a remote userstore.

Fix sub org claim updates when onboarding a remote userstore.

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

$subject
- https://github.com/wso2/product-is/issues/18944

Fix callback url issue in shared applications

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
pom.xml

-  When creating a sub-organization, console and my account applications are shared, Added the relevant access URL for the  apps when sharing.
- https://github.com/wso2/product-is/issues/18933

Add access url for sub organization console and myaccount apps

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

$subject
- https://github.com/wso2/product-is/issues/19037
- https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/261

Fix automatic b2b app owner sharing

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/dao/impl/OrgApplicationMgtDAOImpl.java

>  $subject
- https://github.com/wso2/product-is/issues/19096

Fix multi level organization creation issue for PostgresDB

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.ext/pom.xml
components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

$Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …

Changing snapshot version for next release version

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.ext/pom.xml
components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Reverts wso2-extensions/identity-organization-management#336 since the master is going with latest

Revert "Changing snapshot version for next release version"

---

components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.ext/pom.xml
components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Reverts wso2-extensions/identity-organization-management#337 as we can go with mentioned range

Revert "Revert "Changing snapshot version for next release version""

---

components/org.wso2.carbon.identity.organization.config.service/pom.xml
components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.claim.provider/pom.xml
components/org.wso2.carbon.identity.organization.management.ext/pom.xml
components/org.wso2.carbon.identity.organization.management.governance.connector/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Issue https://github.com/wso2/product-is/issues/19323

Perform minor version bump

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
pom.xml

Issue https://github.com/wso2/product-is/issues/19280

Remove access tokens when unsharing app

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> $subject
- https://github.com/wso2/product-is/issues/19540

Fix application sharing issue

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> $subject
- https://github.com/wso2/product-is/issues/19589

Fix for not removing the organization SSO option when share with all orgs when isAppShared is true

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> $subject
- https://github.com/wso2/product-is/issues/19592

Fix application sharing failed when the organization owner is deleted

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

$Subject
Fix: https://github.com/wso2/product-is/issues/19662

SharedApp inherit api based auth enable property from root app

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Improve fragment apps claims

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingService.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java

Add method to get user associations

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListener.java

Reduce the priority of shared user operation listener

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

$subject
- https://github.com/wso2-extensions/identity-organization-management/pull/330

Add comment for isOAuthClientExistsError method

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/test/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImplTest.java

Unit test for PR https://github.com/wso2-extensions/identity-organization-management/pull/352
Part of https://github.com/wso2/product-is/issues/20014

Add unit test for ConfirmationCodeReturnOnInviteCreation

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

Fix NPE when organization creation with new runtime

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Inherit access url from root application if shared app doesn't have a specified URL

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/handler/UserInvitationEventHandler.java

Add temp logs for user invitation handler

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

>  $subject
- https://github.com/wso2/product-is/issues/20316

Add shared console administrator role when org creation with basic auth

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/handler/UserInvitationEventHandler.java

Improve temp logs for user invitation handler

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/handler/UserInvitationEventHandler.java

Improve logs in parent user invitation event handler

---

components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManagerImpl.java

Attribute existence check for empty attribute values will lead to error in SQL query for `in (list)`.

Skip attribute existence check for empty attribute values

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

>  $subject
- https://github.com/wso2/product-is/issues/20368

Organization creation backward compatibility support according to runtime

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> $subject
- https://github.com/wso2/product-is/issues/20404

Remove user organization claim which is not required for the B2B logins

---

components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.discovery.service/src/test/java/org.wso2.carbon.identity.organization.discovery.service/OrganizationDiscoveryManagerImplTest.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/util/OrgApplicationManagerUtil.java
pom.xml

> $subject
- https://github.com/wso2/product-is/issues/20445

Organization SSO IDP creation improvements

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Fix audit log builder issue when shared application deletion

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
pom.xml

> This PR provides the capability to share the applicationEnabled status to the shared applications.
> Link to the PR for changes …

Inherit app enabled property to the shared apps

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Improve organization SSO IDP fetching logic

---

components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/dao/UserInvitationDAOImpl.java

Improve logs for the parent user invitation creation

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Reverts wso2-extensions/identity-organization-management#380

Revert "Improve organization SSO IDP fetching logic"

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharingOrganizationCreatorUserEventHandler.java

$subject
- https://github.com/wso2-extensions/identity-organization-management/pull/333

Address review comments in PR-333

---

pom.xml

> $subject
Related issue: https://github.com/wso2/product-is/issues/21200 …

Upgrade oAuth component version

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListenerTest.java

Reverts wso2-extensions/identity-organization-management#420

Allow application creation in sub organization level

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandler.java

- $subject
- Part of the implementation for https://github.com/wso2/product-is/issues/21208
- From [1] we are giving the capability to manage applications in organizations. When deleting an organization we need to remove the shared app links from the main app to fragment app. Since we can have non fragment apps in organizations, we can add a get the main application IDs only from the fragment apps.
[1] https://github.com/wso2/product-is/issues/21208

Avoid checking main app ID when the application is not a fragment application during the organization delete

---

components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/pom.xml

$Subject
Fix https://github.com/wso2/product-is/issues/22400

Fix ResourceSharingPolicyHandlerService service not registering issue

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/util/OrganizationSharedUserUtil.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/util/OrganizationSharedUserUtilTest.java

$Subject
isSharedUserProfileResolverEnabled is true when SharedUserProfileUpdateGovernanceEventListener is enabled
Part of https://github.com/wso2/product-is/issues/22126

Add a util method to return isSharedUserProfileResolverEnabled

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> Fix myaccount access url issue.
Issue - https://github.com/wso2/product-is/issues/22358

Fix my account shared app access url issue

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/OrganizationUserSharingHandler.java

Get a new sub-listed ancestor organization list without modifying the original list.

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListenerTest.java

- $subject
- Fixes : https://github.com/wso2/product-is/issues/22569

Delete sub organization application roles when removing from the associated sub organization application

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImpl.java

> This PR fixes an issue in selective user sharing where the policyHoldingOrg was incorrectly set to the organization ID from which the user sharing was initiated, instead of the selected organizations. This caused an error when attempting to share the user with the originating organization itself.
> - Ensure that the `policyHoldingOrg` in selective user sharing corresponds to the selected organizations instead of the initiating organization.
> - Prevent erroneous attempts to share the user with the originating organization.
> - Improve the maintainability of the `shareUser` method by refactoring it into private methods.
> - Updated the `policyHoldingOrg` assignment logic to correctly retrieve the organizations selected for sharing when dealing with `SelectiveUserShare`.
> - Introduced …

Fix policyHoldingOrg for selective user share and refactor shareUser method

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListener.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListenerTest.java

$Subject
Fix: https://github.com/wso2/product-is/issues/22688 and https://github.com/wso2/product-is/issues/22696
Earlier, if the claim value doesn't have any value instead returning null, the claim itself has been droped from userstore manager.
With new listener of resolving claim for shared users, we have added null as claim value if there is no value is resolved.
This PR solves that issue by ignoring the claim fully, if the resolved value is null for the claim.

Stop adding null values to claim values to avoid NPE

---

components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/src/main/java/org/wso2/carbon/identity/organization/resource/sharing/policy/management/dao/ResourceSharingPolicyHandlerDAOImpl.java

$subject
Fixes: https://github.com/wso2/product-is/issues/22671

Remove extra semicolon in Oracle query for getting resource sharing policies

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java

> The current implementation of user share and unshare operations executes synchronously, which may lead to performance bottlenecks when handling multiple organizations. This PR introduces an asynchronous execution approach to improve efficiency.
> - Improve the performance of user share and unshare operations by handling them asynchronously.
> - Ensure proper tenant flow management during execution.
> - Reduce processing time for large-scale user-sharing requests.
> - Refactored user share and unshare operations to execute asynchronously.
> - Introduced a separate method to encapsulate the logic for processing share operations.
> - Ensured proper tenant context switching during execution.
> - Improved logging to track the execution process.
---
[Improve User Share Handling with …

Refactor User Share Operations to Execute Asynchronously

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListener.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserOperationEventListenerTest.java

Fix https://github.com/wso2/product-is/issues/22700

Fix returning shared profile value for claims need to be resolved by origin

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandler.java

Fix https://github.com/wso2/product-is/issues/22841

Check claim dialect existence before adding the dialect to sub orgs

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Fix https://github.com/wso2/product-is/issues/22798

Fix resetting subject claim uri on app sharing

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
pom.xml

Reverts wso2-extensions/identity-organization-management#457

Revert "Inherit main application isDiscoverable property and access url to shared applications. "

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml

Add missing runtime import packages to organization handler

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
pom.xml

Below original pr was reverted as an immediate fix to a cyclic dependency issue occured with the framework version bump. This pr adds the fix again with a framework bump to the latest version after fixing the cyclic dependency
- https://github.com/wso2-extensions/identity-organization-management/pull/457

Inherit main application isDiscoverable property and access url to shared applications.

---

components/org.wso2.carbon.identity.organization.management.authz.service/src/main/java/org/wso2/carbon/identity/organization/management/authz/service/internal/OrganizationManagementAuthzServiceComponent.java

Remove the unused authorization handler used for organization management

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/FragmentApplicationMgtHandler.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/internal/OrganizationManagementHandlerServiceComponent.java

Add handler to manage the application sharing conflicts with sub organizations

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandler.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/handler/OrgClaimMgtHandlerTest.java
components/org.wso2.carbon.identity.organization.management.application/src/test/resources/testng.xml

$subject
- https://github.com/wso2/product-is/issues/22949

Fix attribute mappings and excluded user store property sharing for sub orgs when claim update

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

$subject
Fixes: https://github.com/wso2/product-is/issues/23085

Add warn and diagnostic logging for shared app rename conflicts

---

components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListenerTest.java

Add unit tests to cover handling app role addition when application is updating

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListener.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandlerTest.java
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListenerTest.java
pom.xml

- $subject
- Fix for : https://github.com/wso2/product-is/issues/23427

Handle role conflict when updating the role audience of a shared app to organization

---

components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListenerTest.java

Fix unit test failures for role conflict

---

components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListenerTest.java

Update test methods to return boolean values

---

components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListenerTest.java

Fix unit test failures due to collection empty map

---

components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/AttributeBasedOrganizationDiscoveryHandler.java
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/OrganizationDiscoveryManagerImpl.java
components/org.wso2.carbon.identity.organization.discovery.service/src/test/java/org.wso2.carbon.identity.organization.discovery.service/OrganizationDiscoveryManagerImplTest.java

Update organization discovery to call overloaded method by default

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserProfileUpdateGovernanceEventListener.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/test/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/listener/SharedUserProfileUpdateGovernanceEventListenerTest.java

The purpose of this PR is to resolve the https://github.com/wso2/product-is/issues/23603 where shared users were not identified during user invitation and user sharing flows in **WSO2 IS versions after 7.1.0**. Since user associations are not established at the time of shared user creation, the system failed to recognize shared users, resulting in incorrect processing.  
- Ensure shared users are correctly identified during the user invitation and user sharing flows.  
- Provide a reliable mechanism to distinguish shared users from regular users at the point of creation.  
- Prevent further issues caused by the absence of proper identification.  
- Maintain compatibility with existing user identification logic for other scenarios.  
- Initiated a tenant flow during the shared user …

Fix Shared User Identification During Invitation and Sharing Flows

---

components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/listener/SharedRoleMgtListenerTest.java

Temporarily remove SharedRoleMgtListener unit tests

---

components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/listener/OrganizationDiscoveryUserOperationListener.java
components/org.wso2.carbon.identity.organization.discovery.service/src/test/java/org.wso2.carbon.identity.organization.discovery.service/listener/OrganizationDiscoveryUserOperationListenerTest.java

$subject
- https://github.com/wso2/product-is/issues/23855

Skip domain validation for shared users

---

components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/src/test/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandlerTest.java
components/org.wso2.carbon.identity.organization.user.invitation.management/src/main/java/org/wso2/carbon/identity/organization/user/invitation/management/InvitationCoreServiceImpl.java

Add review suggestions

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

> $subject
Related Issues:
- https://github.com/wso2/product-is/issues/23462

Resolve tenant domain by org id

---

components/org.wso2.carbon.identity.organization.management.claim.provider/src/main/java/org/wso2/carbon/identity/organization/management/claim/provider/OrganizationClaimProvider.java

> $subject
Resolves https://github.com/wso2/product-is/issues/23663

Resolve user org from authorized user

---

components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/OrganizationUserSharingServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/UserSharingPolicyHandlerServiceImpl.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/constant/UserSharingConstants.java

Reverts wso2-extensions/identity-organization-management#528

Revert "Fix username validation during agent sharing "

---

pom.xml

Add project.scm.id property for release build failure fix

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

Refactor resolution of general sharing mode for backward compatibility of isShareWithAllChildren property

---

components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandler.java

Fix searching org roles with main org associations

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandler.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandlerTest.java
components/org.wso2.carbon.identity.organization.management.application/src/test/resources/testng.xml

$subject
Issue: https://github.com/wso2/product-is/issues/24949

Change log level from error to debug for missing shared application case

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/util/OrgApplicationManagerUtil.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/OrganizationCreationHandlerTest.java

When updating SP properties,
- Make sure not to update already updated properties to optimize the performance
- Update SP properties of system applications properly
- Make sure to properly add remove shareWithAllChildren property
- Added the same changes of https://github.com/wso2-extensions/identity-organization-management/pull/547
- https://github.com/wso2/product-is/issues/24887

Update SP properties for sharing applications properly

---

.github/copilot-instructions.md

Add custom co-pilot instructions

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java

Fix organization management exception error message in doPreDeleteApplication listener

---

components/org.wso2.carbon.identity.organization.application.resource.hierarchy.traverse.service/pom.xml
components/org.wso2.carbon.identity.organization.config.service/pom.xml
components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.management.application/pom.xml
components/org.wso2.carbon.identity.organization.management.authz.service/pom.xml
components/org.wso2.carbon.identity.organization.management.claim.provider/pom.xml
components/org.wso2.carbon.identity.organization.management.ext/pom.xml
components/org.wso2.carbon.identity.organization.management.governance.connector/pom.xml
components/org.wso2.carbon.identity.organization.management.handler/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.role.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.tenant.association/pom.xml
components/org.wso2.carbon.identity.organization.management.tomcat.ext.tenant.resolver/pom.xml
components/org.wso2.carbon.identity.organization.resource.hierarchy.traverse.service/pom.xml
components/org.wso2.carbon.identity.organization.resource.sharing.policy.management/pom.xml
components/org.wso2.carbon.identity.organization.user.invitation.management/pom.xml
features/org.wso2.carbon.identity.organization.management.server.feature/pom.xml
pom.xml

Add the `next` suffix to the POM versions.
- https://github.com/wso2/product-is/issues/24775

[IS 7.2.0 POST ALPHA] Update `next` branch versions

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

A shared app's callback URL is the parent org's commonauth URL. The commonauth url of the parent org can change only upon a hostname change. To handle this, we are adding the placeholder value to db and building the URL upon accessing.
Also, we are skipping domain branding when sharing Console and MyAccount.
Related PRs
https://github.com/wso2/carbon-identity-framework/pull/7035
Issue : 
https://github.com/wso2/product-is/issues/24275

Add placeholder for shared app callbackURL & skip domain branding for Console and MyAccount

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/constant/OrgApplicationMgtConstants.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImplTest.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/SharedRoleMgtHandler.java

$subject
- https://github.com/wso2/product-is/issues/25235

Skip hierarchy

---

.github/copilot-instructions.md

Update instructions to check security issues

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/OrgApplicationManagerImpl.java

$subject
- https://github.com/wso2/product-is/issues/25515

Set is app shared property

---

components/org.wso2.carbon.identity.organization.discovery.service/pom.xml
components/org.wso2.carbon.identity.organization.discovery.service/src/main/java/org/wso2/carbon/identity/organization/discovery/service/listener/OrganizationDiscoveryUserOperationListener.java
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/pom.xml
components/org.wso2.carbon.identity.organization.management.organization.user.sharing/src/main/java/org/wso2/carbon/identity/organization/management/organization/user/sharing/util/OrganizationSharedUserUtil.java

Extract isSharedUser to a util method

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListenerTest.java
pom.xml

> $Subject
Issue - https://github.com/wso2/product-is/issues/25620
Depends on - https://github.com/wso2/identity-organization-management-core/pull/208

Add support for adaptive scripts in shared apps based on a config

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/internal/OrgApplicationMgtServiceComponent.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/MainApplicationEventListener.java
components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/SharedApplicationEventListener.java
components/org.wso2.carbon.identity.organization.management.handler/src/main/java/org/wso2/carbon/identity/organization/management/handler/SharingPolicyCleanUpHandler.java
pom.xml

$subject
- https://github.com/wso2/product-is/issues/25474
*** Notes: Merged after https://github.com/wso2/carbon-identity-framework/pull/7303

Add resource clean up for application

---

components/org.wso2.carbon.identity.organization.management.application/src/main/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListener.java
components/org.wso2.carbon.identity.organization.management.application/src/test/java/org/wso2/carbon/identity/organization/management/application/listener/FragmentApplicationMgtListenerTest.java

Add the default authentication of the application as fallback when only organization SSO option is configured as the first step for a shared application, which causes error when the application is unshared.
- https://github.com/wso2/product-is/issues/21714

[bug-fix] Fix organization SSO login issues
